name: Sync Snowflake Configuration to Pulumi ESC

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/snowflake-config-sync.yml'
  schedule:
    - cron: '0 0 * * MON' # Weekly sync on Mondays

jobs:
  sync-snowflake-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pulumi
        uses: pulumi/actions@v4

      - name: Configure Pulumi ESC
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi login

      - name: Sync Snowflake Configuration
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          # Set Snowflake configuration in Pulumi ESC
          echo "Setting Snowflake configuration in Pulumi ESC..."

          pulumi env set scoobyjava-org/default/sophia-ai-production \
            snowflake_account "$SNOWFLAKE_ACCOUNT" \
            snowflake_user "$SNOWFLAKE_USER" \
            snowflake_password "$SNOWFLAKE_PASSWORD" --secret \
            snowflake_role "$SNOWFLAKE_ROLE" \
            snowflake_warehouse "$SNOWFLAKE_WAREHOUSE" \
            snowflake_database "$SNOWFLAKE_DATABASE" \
            snowflake_schema "$SNOWFLAKE_SCHEMA"

          echo "✅ Snowflake configuration synced to Pulumi ESC"

      - name: Verify Configuration
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          echo "Verifying Snowflake configuration..."
          pulumi env get scoobyjava-org/default/sophia-ai-production | grep snowflake || echo "No Snowflake config found"
