apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-unified-backend
  namespace: sophia-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sophia-unified-backend
  template:
    metadata:
      labels:
        app: sophia-unified-backend
    spec:
      containers:
        - name: sophia-unified-backend
          image: scoobyjava15/sophia-unified-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: sophia-secrets
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-unified-backend-service
  namespace: sophia-ai
spec:
  type: ClusterIP
  selector:
    app: sophia-unified-backend
  ports:
    - port: 80
      targetPort: 8000
