"""
"""
    """
    """
            "requests_processed"
            "errors_count"
            "last_activity"
        """Initialize the consolidated service"""
logger.info("✅ UnifiedChatService initialized with consolidated services"
            self.metrics["last_activity"
            logger.info(f"UnifiedChatService initialized successfully"
            logger.error(f"Failed to initialize UnifiedChatService: {e}"
        """Process a request using consolidated logic"""
            self.metrics["requests_processed"
            self.metrics["last_activity"
            logger.error(f"❌ Chat processing failed: {e}"
                "status": "success"
                "service": "UnifiedChatService"
                "processed_at"
                "request_id": self.metrics["requests_processed"
            self.metrics["errors_count"
            logger.error(f"Error processing request in UnifiedChatService: {e}"
                "status": "error"
                "error"
                "service": "UnifiedChatService"
        """Get service metrics"""
        """Perform health check"""
            "status": "healthy" if self.initialized else "unhealthy"
            "service": "UnifiedChatService"
            "metrics"
            "timestamp"