version: "3.8"

services:
  sophia-containerized:
    build:
      context: .
      dockerfile: Dockerfile.uv.containerized
    container_name: sophia-ai-containerized
    ports:
      - "8000:8000"
    environment:
      - SOPHIA_HOST=0.0.0.0
      - SOPHIA_PORT=8000
      - SOPHIA_RELOAD=false
      - PULUMI_ORG=scoobyjava-org
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - sophia-network

networks:
  sophia-network:
    driver: bridge
