apiVersion: v1
data:
  alert_rules.yml: "groups:\n- name: sophia-ai-alerts\n  rules:\n  - alert: HighAPIResponseTime\n\
    \    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))\
    \ > 0.2\n    for: 2m\n    labels:\n      severity: warning\n    annotations:\n\
    \      summary: \"High API response time detected\"\n      description: \"95th\
    \ percentile response time is {{ $value }}s\"\n      \n  - alert: LowN8NThroughput\n\
    \    expr: rate(n8n_workflow_executions_total[5m]) < 220\n    for: 5m\n    labels:\n\
    \      severity: critical\n    annotations:\n      summary: \"N8N throughput below\
    \ target\"\n      description: \"Current throughput: {{ $value }}/s (target: >220/s)\"\
    \n      \n  - alert: HighEstuaryLatency\n    expr: estuary_flow_latency_ms > 100\n\
    \    for: 1m\n    labels:\n      severity: warning\n    annotations:\n      summary:\
    \ \"Estuary Flow latency above target\"\n      description: \"Current latency:\
    \ {{ $value }}ms (target: <100ms)\"\n      \n  - alert: PodCrashLooping\n    expr:\
    \ rate(kube_pod_container_status_restarts_total[15m]) > 0\n    for: 5m\n    labels:\n\
    \      severity: critical\n    annotations:\n      summary: \"Pod is crash looping\"\
    \n      description: \"Pod {{ $labels.pod }} in namespace {{ $labels.namespace\
    \ }} is restarting\"\n"
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: sophia-ai
