apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sophia-ai-prod
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
    - job_name: 'sophia-backend'
      static_configs:
      - targets: ['sophia-backend:8000']
      metrics_path: /metrics
    
    - job_name: 'mcp-servers'
      static_configs:
      - targets: 
        - 'mcp-ai-memory:9000'
        - 'mcp-gong:9001'
        - 'mcp-modern_stack:9002'
        - 'mcp-slack:9003'
        - 'mcp-linear:9004'
        - 'mcp-github:9005'
        - 'mcp-codacy:9006'
        - 'mcp-asana:9007'
      metrics_path: /metrics
    
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
