apiVersion: v1
data:
  prometheus.yml: "global:\n  scrape_interval: 15s\n  evaluation_interval: 15s\n\n\
    scrape_configs:\n# Docker Build Cloud metrics\n- job_name: 'docker-build-cloud'\n\
    \  static_configs:\n  - targets: ['build-metrics.docker.com:443']\n  scheme: https\n\
    \  metrics_path: '/metrics'\n  \n# N8N performance metrics\n- job_name: 'n8n-main'\n\
    \  kubernetes_sd_configs:\n  - role: pod\n    namespaces:\n      names: ['sophia-ai']\n\
    \  relabel_configs:\n  - source_labels: [__meta_kubernetes_pod_label_app]\n  \
    \  regex: n8n-main\n    action: keep\n\n- job_name: 'n8n-workers'\n  kubernetes_sd_configs:\n\
    \  - role: pod\n    namespaces:\n      names: ['sophia-ai']\n  relabel_configs:\n\
    \  - source_labels: [__meta_kubernetes_pod_label_app]\n    regex: n8n-worker\n\
    \    action: keep\n\n# Estuary Flow metrics\n- job_name: 'estuary-flow'\n  static_configs:\n\
    \  - targets: ['flow-metrics.estuary.dev:443']\n  scheme: https\n  \n# Sophia\
    \ AI application metrics\n- job_name: 'sophia-ai'\n  kubernetes_sd_configs:\n\
    \  - role: pod\n    namespaces:\n      names: ['sophia-ai']\n  relabel_configs:\n\
    \  - source_labels: [__meta_kubernetes_pod_label_app]\n    regex: sophia-ai\n\
    \    action: keep\n\nrule_files:\n- \"alert_rules.yml\"\n\nalerting:\n  alertmanagers:\n\
    \  - static_configs:\n    - targets: ['alertmanager:9093']\n"
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sophia-ai
