# PERMANENT SECRET MAPPING - THE SOURCE OF TRUTH
# This file maps GitHub secret names to application configuration keys
# GitHub secrets -> Pulumi ESC -> Application

# DOCKER HUB CREDENTIALS
docker:
  github_secrets:
    username: DOCKER_USERNAME  # The actual GitHub secret name
    token: DOCKER_TOKEN       # The actual GitHub secret name
  
  application_keys:  # All the ways the app might ask for these
    username:
      - docker_username
      - docker_hub_username
      - DOCKER_USERNAME
      - DOCKERHUB_USERNAME
      - DOCKER_USER_NAME
    token:
      - docker_token
      - docker_hub_token
      - docker_hub_access_token
      - docker_password
      - DOCKER_TOKEN
      - DOCKER_PASSWORD
      - DOCKER_PERSONAL_ACCESS_TOKEN
      - DOCKER_HUB_ACCESS_TOKEN

# SNOWFLAKE CREDENTIALS
snowflake:
  github_secrets:
    account: SNOWFLAKE_ACCOUNT
    user: SNOWFLAKE_USER
    password: SNOWFLAKE_PASSWORD  # This is the PAT
    warehouse: SNOWFLAKE_WAREHOUSE
    database: SNOWFLAKE_DATABASE
    schema: SNOWFLAKE_SCHEMA
    role: SNOWFLAKE_ROLE
  
  application_keys:
    account:
      - snowflake_account
      - SNOWFLAKE_ACCOUNT
    user:
      - snowflake_user
      - SNOWFLAKE_USER
    password:
      - snowflake_password
      - snowflake_pat
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_PAT

# LAMBDA LABS
lambda:
  github_secrets:
    api_key: LAMBDA_API_KEY
    ssh_key: LAMBDA_SSH_PRIVATE_KEY
  
  application_keys:
    api_key:
      - lambda_api_key
      - LAMBDA_API_KEY
    ssh_key:
      - lambda_ssh_private_key
      - lambda_ssh_key
      - LAMBDA_SSH_PRIVATE_KEY
      - LAMBDA_SSH_KEY

# AI SERVICES
ai_services:
  github_secrets:
    openai: OPENAI_API_KEY
    anthropic: ANTHROPIC_API_KEY
    pinecone: PINECONE_API_KEY
  
  application_keys:
    openai:
      - openai_api_key
      - OPENAI_API_KEY
    anthropic:
      - anthropic_api_key
      - ANTHROPIC_API_KEY
    pinecone:
      - pinecone_api_key
      - PINECONE_API_KEY

# DEVELOPMENT TOOLS
dev_tools:
  github_secrets:
    github: GH_API_TOKEN
    linear: LINEAR_API_KEY
    notion: NOTION_API_KEY
    figma: FIGMA_PAT
    vercel: VERCEL_TOKEN
  
  application_keys:
    github:
      - github_token
      - gh_api_token
      - GH_API_TOKEN
      - GITHUB_TOKEN
    linear:
      - linear_api_key
      - LINEAR_API_KEY
    notion:
      - notion_api_key
      - notion_api_token
      - NOTION_API_KEY
      - NOTION_API_TOKEN

# BUSINESS TOOLS
business_tools:
  github_secrets:
    gong_key: GONG_ACCESS_KEY
    gong_secret: GONG_ACCESS_KEY_SECRET
    hubspot: HUBSPOT_API_KEY
    slack_webhook: SLACK_WEBHOOK
    slack_bot: SLACK_BOT_TOKEN
  
  application_keys:
    gong_key:
      - gong_access_key
      - GONG_ACCESS_KEY
    gong_secret:
      - gong_access_key_secret
      - GONG_ACCESS_KEY_SECRET
    hubspot:
      - hubspot_api_key
      - hubspot_access_token
      - HUBSPOT_API_KEY
      - HUBSPOT_ACCESS_TOKEN 