
-- ==================================================
-- SOPHIA AI PHASE 1: CUSTOMER INSIGHTS FOUNDATION
-- ==================================================

-- Main customer insights schema
-- Note: Using standard SQL schema creation without database-specific statements
CREATE SCHEMA CUSTOMER_INTELLIGENCE;

-- =================
-- CORE TABLES
-- =================

-- Customer profiles with AI enrichment
CREATE TABLE CUSTOMER_PROFILES (
    customer_id VARCHAR(50) PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    company VARCHAR(255),
    industry VARCHAR(100),
    customer_tier VARCHAR(20), -- Enterprise, SMB, Startup
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_interaction_date TIMESTAMP,
    total_revenue DECIMAL(15,2) DEFAULT 0,
    health_score DECIMAL(3,2), -- 0.0 to 1.0
    churn_risk_score DECIMAL(3,2), -- 0.0 to 1.0
    growth_potential_score DECIMAL(3,2), -- 0.0 to 1.0
    -- Standard SQL doesn't have vector types, using VARCHAR for serialized vectors
    customer_embedding VARCHAR(8000), -- AI customer representation (serialized)
    profile_summary TEXT,
    ai_insights TEXT,
    created_by VARCHAR(100) DEFAULT 'sophia_ai',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Customer interactions across all touchpoints
CREATE TABLE CUSTOMER_INTERACTIONS (
    interaction_id VARCHAR(50) PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    interaction_type VARCHAR(50), -- call, email, meeting, support, demo
    interaction_date TIMESTAMP NOT NULL,
    interaction_content TEXT,
    interaction_summary TEXT,
    sentiment_score DECIMAL(3,2), -- -1.0 to 1.0
    -- Standard SQL doesn't have array types, using VARCHAR for serialized lists
    topics VARCHAR(4000),
    key_insights VARCHAR(4000),
    action_items VARCHAR(4000),
    deal_impact VARCHAR(20), -- positive, negative, neutral
    urgency_level VARCHAR(20), -- low, medium, high, critical
    interaction_embedding VARCHAR(8000),
    source_system VARCHAR(50), -- gong, hubspot, slack, linear
    source_id VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES CUSTOMER_PROFILES(customer_id)
);

-- Customer journey stages and progression
CREATE TABLE CUSTOMER_JOURNEY (
    journey_id VARCHAR(50) PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    journey_stage VARCHAR(50), -- prospect, demo, negotiation, closed_won, expansion, renewal, churn
    stage_entered_date TIMESTAMP NOT NULL,
    stage_duration_days INTEGER,
    stage_success_probability DECIMAL(3,2),
    -- Standard SQL doesn't have array types, using VARCHAR for serialized lists
    stage_blockers VARCHAR(4000),
    stage_accelerators VARCHAR(4000),
    next_best_action TEXT,
    ai_recommendations VARCHAR(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES CUSTOMER_PROFILES(customer_id)
);

-- =================
-- AI ENRICHMENT TABLES
-- =================

-- Customer insights generated by AI
CREATE TABLE CUSTOMER_AI_INSIGHTS (
    insight_id VARCHAR(50) PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    insight_type VARCHAR(50), -- behavior_pattern, growth_opportunity, risk_factor, recommendation
    insight_title VARCHAR(255),
    insight_description TEXT,
    confidence_score DECIMAL(3,2),
    impact_score DECIMAL(3,2), -- potential business impact
    -- Standard SQL doesn't have array types, using VARCHAR for serialized lists
    evidence VARCHAR(4000), -- supporting data points
    recommended_actions VARCHAR(4000),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_date TIMESTAMP, -- when insight becomes stale
    status VARCHAR(20) DEFAULT 'active', -- active, acted_upon, expired
    FOREIGN KEY (customer_id) REFERENCES CUSTOMER_PROFILES(customer_id)
);

-- Predictive analytics for customers
CREATE TABLE CUSTOMER_PREDICTIONS (
    prediction_id VARCHAR(50) PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    prediction_type VARCHAR(50), -- churn_risk, expansion_opportunity, renewal_likelihood
    prediction_value DECIMAL(10,4),
    prediction_confidence DECIMAL(3,2),
    -- Standard SQL doesn't have array types, using VARCHAR for serialized lists
    prediction_factors VARCHAR(4000),
    prediction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    prediction_horizon_days INTEGER, -- how many days into future
    model_version VARCHAR(20),
    actuals_value DECIMAL(10,4), -- actual outcome when available
    prediction_accuracy DECIMAL(3,2), -- accuracy when actuals available
    FOREIGN KEY (customer_id) REFERENCES CUSTOMER_PROFILES(customer_id)
);

-- =================
-- PERFORMANCE TRACKING
-- =================

-- Customer success metrics
CREATE TABLE CUSTOMER_SUCCESS_METRICS (
    metric_id VARCHAR(50) PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    metric_date DATE NOT NULL,
    metric_type VARCHAR(50), -- usage, adoption, satisfaction, value_realization
    metric_value DECIMAL(15,4),
    metric_target DECIMAL(15,4),
    metric_variance_pct DECIMAL(5,2),
    trend_direction VARCHAR(10), -- up, down, stable
    benchmark_percentile INTEGER, -- vs other customers
    -- Standard SQL doesn't have array types, using VARCHAR for serialized lists
    improvement_suggestions VARCHAR(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES CUSTOMER_PROFILES(customer_id)
);
