networks:
  sophia-staging-network:
    external: true
services:
  ai-memory-mcp:
    container_name: ai-memory-mcp-staging
    environment:
    - MCP_SERVER_PORT=9001
    - ENVIRONMENT=staging
    networks:
    - sophia-staging-network
    ports:
    - 9001:9001
  redis-cluster:
    container_name: redis-staging
    networks:
    - sophia-staging-network
    ports:
    - 6380:6379
    volumes:
    - sophia-staging-data:/data
  sophia-backend:
    container_name: sophia-backend-staging
    environment:
    - SOPHIA_ENVIRONMENT=staging
    - SOPHIA_PORT=8001
    - DEBUG=true
    - LOG_LEVEL=DEBUG
    networks:
    - sophia-staging-network
    ports:
    - 8001:8001
    volumes:
    - sophia-staging-logs:/app/logs
    - sophia-staging-cache:/app/cache
version: '3.8'
volumes:
  sophia-staging-cache:
    external: true
  sophia-staging-data:
    external: true
  sophia-staging-logs:
    external: true
