networks:
  sophia-staging:
    external: true
services:
  postgres-staging:
    container_name: postgres-staging
    environment:
    - POSTGRES_DB=sophia_staging
    - POSTGRES_USER=sophia
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD-SHELL
      - pg_isready -U sophia -d sophia_staging
      timeout: 10s
    image: postgres:15-alpine
    networks:
    - sophia-staging
    ports:
    - 5433:5432
    restart: unless-stopped
  redis-staging:
    command: redis-server --appendonly yes
    container_name: redis-staging
    image: redis:7-alpine
    networks:
    - sophia-staging
    ports:
    - 6380:6379
    restart: unless-stopped
  sophia-backend-staging:
    build:
      context: .
      dockerfile: Dockerfile.uv.staging
    container_name: sophia-backend-staging
    depends_on:
    - redis-staging
    - postgres-staging
    environment:
    - SOPHIA_ENVIRONMENT=staging
    - SOPHIA_PORT=8000
    - POSTGRES_HOST=postgres-staging
    - REDIS_HOST=redis-staging
    - DEBUG=true
    networks:
    - sophia-staging
    ports:
    - 8001:8000
    restart: unless-stopped
