version: '3.8'

# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose in development

services:
  mcp-gateway:
    build: ./mcp-gateway
    volumes:
      - ./mcp-gateway:/app
    ports:
      - "3000:3000"
      - "8090:8090"
  github-mcp:
    build: ./mcp-servers/github
    volumes:
      - ./mcp-servers/github:/app
    ports:
      - "3002:3002"
  docker-mcp:
    build: ./mcp-servers/docker
    volumes:
      - ./mcp-servers/docker:/app
    ports:
      - "3003:3003"
  slack-mcp:
    build: ./mcp-servers/slack
    volumes:
      - ./mcp-servers/slack:/app
    ports:
      - "3004:3004"
  postgres-mcp:
    build: ./mcp-servers/postgres
    volumes:
      - ./mcp-servers/postgres:/app
    ports:
      - "3005:3005"
  pulumi-mcp:
    build:
      context: .
      dockerfile: mcp-servers/pulumi/Dockerfile
    volumes:
      - ./mcp-servers/pulumi:/app
    ports:
      - "3001:3001"
  sentry-mcp:
    build:
      context: .
      dockerfile: mcp-servers/sentry/Dockerfile
    volumes:
      - ./mcp-servers/sentry:/app
    ports:
      - "9006:9000"
  sophia_ai_intelligence-mcp:
    build:
      context: .
      dockerfile: mcp-servers/sophia_ai_intelligence/Dockerfile
    volumes:
      - ./mcp-servers/sophia_ai_intelligence:/app
  sophia_business_intelligence-mcp:
    build:
      context: .
      dockerfile: mcp-servers/sophia_business_intelligence/Dockerfile
    volumes:
      - ./mcp-servers/sophia_business_intelligence:/app
  sophia_data_intelligence-mcp:
    build:
      context: .
      dockerfile: mcp-servers/sophia_data_intelligence/Dockerfile
    volumes:
      - ./mcp-servers/sophia_data_intelligence:/app
  sophia_infrastructure-mcp:
    build:
      context: .
      dockerfile: mcp-servers/sophia_infrastructure/Dockerfile
    volumes:
      - ./mcp-servers/sophia_infrastructure:/app

  sophia-backend:
    build:
      target: development
    volumes:
      # Mount source code for hot reload
      - ./backend:/app/backend:cached
      - ./config:/app/config:cached
      - ./pyproject.toml:/app/pyproject.toml:cached
      # Exclude Python cache
      - /app/backend/__pycache__
      - /app/backend/**/__pycache__
    environment:
      - ENVIRONMENT=dev
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    ports:
      - "8000:8000"
      - "5678:5678"  # Python debugger port
    command: ["uvicorn", "backend.app.unified_fastapi_app:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]

  mem0-server:
    volumes:
      - ./backend/mcp_servers/mem0_openmemory:/app:cached
    environment:
      - LOG_LEVEL=DEBUG

  cortex-server:
    volumes:
      - ./backend/mcp_servers/cortex_aisql:/app:cached
    environment:
      - LOG_LEVEL=DEBUG

  # Development tools
  mailhog:
    image: mailhog/mailhog:latest
    container_name: sophia-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    profiles:
      - dev-tools
    networks:
      - sophia-network

  # Jupyter for data exploration
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: sophia-jupyter
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./backend:/app/backend
    environment:
      - JUPYTER_ENABLE_LAB=yes
    profiles:
      - dev-tools
    networks:
      - sophia-network 