version: '3.8'

services:
  backend:
    image: scoobyjava15/sophia-ai:latest
    container_name: sophia-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PULUMI_ORG=scoobyjava-org
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - sophia-network

  frontend:
    image: scoobyjava15/sophia-frontend:latest
    container_name: sophia-frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sophia-network

  mcp-ai-memory:
    image: scoobyjava15/sophia-mcp:ai-memory
    container_name: sophia-mcp-ai-memory
    ports:
      - "9000:9000"
    environment:
      - ENVIRONMENT=production
      - PULUMI_ORG=scoobyjava-org
    restart: unless-stopped
    networks:
      - sophia-network

  mcp-snowflake:
    image: scoobyjava15/sophia-mcp:snowflake
    container_name: sophia-mcp-snowflake
    ports:
      - "9011:9011"
    environment:
      - ENVIRONMENT=production
      - PULUMI_ORG=scoobyjava-org
    restart: unless-stopped
    networks:
      - sophia-network

networks:
  sophia-network:
    driver: bridge
