version: '3.8'

services:
  backend:
    image: scoobyjava15/sophia-ai-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - PULUMI_STACK=sophia-ai-production
      - DOMAIN=sophia-intel.ai
      - LOG_LEVEL=INFO
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - GONG_API_KEY=${GONG_API_KEY}
      - HUBSPOT_API_KEY=${HUBSPOT_API_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
