# WARNING: This file is part of the future monorepo structure.
# DO NOT USE until migration is complete (Target: February 2025)
# See docs/monorepo/MONOREPO_TRANSITION_GUIDE.md for details

packages:
  # Applications (NOT YET ACTIVE)
  - "apps/*"
  # Shared libraries (NOT YET ACTIVE)
  - "libs/*"
  # Configuration packages (NOT YET ACTIVE)
  - "config/*"
