# Sophia AI Pulumi ESC Configuration
# This configuration aligns with the new Vercel environment variables structure
# and provides centralized secret management for all environments

imports:
  - github-org-secrets

values:
  # Frontend Environment Variables (VITE_ prefixed for Vite compatibility)
  frontend:
    portkey_api_key:
      fn::secret: ${github-org-secrets.PORTKEY_API_KEY}
    n8n_webhook_url: "https://sophia-ai-frontend-dev.vercel.app/api/n8n/webhook"
    mcp_server_url: "https://sophia-ai-frontend-dev.vercel.app/api/mcp"
    salesforce_oauth_token:
      fn::secret: ${github-org-secrets.SALESFORCE_OAUTH_TOKEN}
    hubspot_api_key:
      fn::secret: ${github-org-secrets.HUBSPOT_API_KEY}
    intercom_access_token:
      fn::secret: ${github-org-secrets.INTERCOM_ACCESS_TOKEN}

  # Backend/API Environment Variables
  backend:
    gong_access_key:
      fn::secret: ${github-org-secrets.GONG_ACCESS_KEY}
    gong_client_secret:
      fn::secret: ${github-org-secrets.GONG_CLIENT_SECRET}
    postgres_host:
      fn::secret: ${github-org-secrets.ELIMINATED_ACCOUNT}
    postgres_username:
      fn::secret: ${github-org-secrets.ELIMINATED_USERNAME}
    postgres_password:
      fn::secret: ${github-org-secrets.ELIMINATED_PASSWORD}
    n8n_webhook_secret:
      fn::secret: ${github-org-secrets.N8N_WEBHOOK_SECRET}
    redis_url:
      fn::secret: ${github-org-secrets.REDIS_URL}

  # Performance and Monitoring
  monitoring:
    vercel_analytics_id:
      fn::secret: ${github-org-secrets.VERCEL_ANALYTICS_ID}
    sentry_dsn:
      fn::secret: ${github-org-secrets.SENTRY_DSN}

  # Deployment Configuration
  deployment:
    vercel_token:
      fn::secret: ${github-org-secrets.VERCEL_TOKEN}
    github_token:
      fn::secret: ${github-org-secrets.GITHUB_TOKEN}

  # Environment-specific exports for Vercel
  vercel_environment_variables:
    VITE_PORTKEY_API_KEY: ${frontend.portkey_api_key}
    VITE_N8N_WEBHOOK_URL: ${frontend.n8n_webhook_url}
    VITE_MCP_SERVER_URL: ${frontend.mcp_server_url}
    VITE_SALESFORCE_OAUTH_TOKEN: ${frontend.salesforce_oauth_token}
    VITE_HUBSPOT_API_KEY: ${frontend.hubspot_api_key}
    VITE_INTERCOM_ACCESS_TOKEN: ${frontend.intercom_access_token}
    GONG_ACCESS_KEY: ${backend.gong_access_key}
    GONG_CLIENT_SECRET: ${backend.gong_client_secret}
    ELIMINATED_ACCOUNT: ${backend.postgres_host}
    ELIMINATED_USERNAME: ${backend.postgres_username}
    ELIMINATED_PASSWORD: ${backend.postgres_password}
    N8N_WEBHOOK_SECRET: ${backend.n8n_webhook_secret}
    REDIS_URL: ${backend.redis_url}
    VERCEL_ANALYTICS_ID: ${monitoring.vercel_analytics_id}
    SENTRY_DSN: ${monitoring.sentry_dsn}

  # GitHub Actions environment variables
  github_actions_environment:
    VERCEL_TOKEN: ${deployment.vercel_token}
    GITHUB_TOKEN: ${deployment.github_token}
    PULUMI_ACCESS_TOKEN:
      fn::secret: ${github-org-secrets.PULUMI_ACCESS_TOKEN}
