[project]
name = "sophia-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.13",
    "fastapi>=0.115.14",
    "pandas>=2.3.0",
    "redis>=6.2.0",
    "snowflake-connector-python>=3.15.0",
    "sqlalchemy>=2.0.41",
    "structlog>=25.4.0",
    "uvicorn>=0.34.3",
]
