#!/bin/bash
# Set all secrets in Pulumi ESC from GitHub secrets
# Run this after exporting all GitHub secrets as environment variables

set -e

echo "🔧 Setting all secrets in Pulumi ESC..."

pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.openai.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.anthropic.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.perplexity.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.claude.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.gemini.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.deepseek.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.data.estuary.access_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.data.estuary.client_id "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.data.estuary.client_secret "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.data.estuary.api_url "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.data.estuary.refresh_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.business.gong.access_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.business.gong.instance_url "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.business.hubspot.access_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.business.hubspot.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.business.apollo.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.communication.slack.bot_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.communication.slack.app_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.communication.slack.signing_secret "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.communication.linear.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.qdrant.account "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.qdrant.user "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.qdrant.password "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.qdrant.database "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.qdrant.warehouse "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.qdrant.role "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.data.pinecone.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.data.pinecone.environment "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.data.weaviate.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.data.weaviate.url "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.postgres.password "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.redis.password "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.lambda_labs.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.lambda_labs.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.vercel.api_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.vercel.project_id "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.infrastructure.pulumi.access_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.development.github.token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.development.github.token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.development.codacy.api_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.development.notion.api_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.development.notion.api_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.development.asana.access_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.development.asana.access_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.portkey.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.openrouter.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.development.figma.pat "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.development.figma.project_id "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.integrations.apify.api_token "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.integrations.bright_data.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.huggingface.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.monitoring.sentry.dsn "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.integrations.graphiti.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.monitoring.langfuse.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.monitoring.langsmith.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.integrations.n8n.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.ai.qdrant_memory.api_key "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.security.agent_communication_secret "${github_secret}"
pulumi env set scoobyjava-org/default/sophia-ai-production values.sophia.security.agent_orchestrator_auth_token "${github_secret}"

echo "✅ All secrets set in Pulumi ESC!"
