# Pulumi ESC Environment Configuration for Lambda Labs
# Organization: ai-cherry
# Environment: lambda-labs-production

values:
  # Lambda Labs credentials from GitHub Organization Secrets
  lambda:
    api_key:
      fn::secret: ${github.secrets.LAMBDA_API_KEY}
    ssh_key:
      fn::secret: ${github.secrets.LAMBDA_SSH_KEY}
    private_key:
      fn::secret: ${github.secrets.LAMBDA_PRIVATE_SSH_KEY}

  # Pulumi access token
  pulumi:
    access_token:
      fn::secret: ${github.secrets.PULUMI_ACCESS_TOKEN}

  # Lambda Labs instance configuration
  instances:
    sophia_ai_core:
      name: "sophia-ai-core"
      ip: "192.222.58.232"
      gpu: "GH200"
      memory: "96GB"
      cost_hourly: 1.49
      cost_daily: 35.76
      region: "us-east-3"
      purpose: "Primary AI Core"

    sophia_mcp_orchestrator:
      name: "sophia-mcp-orchestrator"
      ip: "104.171.202.117"
      gpu: "A6000"
      memory: "48GB"
      cost_hourly: 0.80
      cost_daily: 19.20
      region: "us-south-1"
      purpose: "MCP Orchestration"

    sophia_data_pipeline:
      name: "sophia-data-pipeline"
      ip: "104.171.202.134"
      gpu: "A100"
      memory: "40GB"
      cost_hourly: 1.29
      cost_daily: 30.96
      region: "us-south-1"
      purpose: "Data Processing"

    sophia_development:
      name: "sophia-development"
      ip: "155.248.194.183"
      gpu: "A10"
      memory: "24GB"
      cost_hourly: 0.75
      cost_daily: 18.00
      region: "us-west-1"
      purpose: "Development"

  # Service endpoints
  services:
    backend:
      url: "http://192.222.58.232:8000"
      health_endpoint: "/health"
      instance: "sophia_ai_core"

    mcp_orchestrator:
      url: "http://104.171.202.117:8001"
      health_endpoint: "/health"
      instance: "sophia_mcp_orchestrator"

  # Cost tracking
  costs:
    total_hourly: 4.33
    total_daily: 103.92
    total_monthly: 3117.60
    total_yearly: 37411.20

  # Deployment configuration
  deployment:
    docker_registry: "scoobyjava15"
    image_prefix: "sophia-ai"
    environment: "production"

  # Monitoring configuration
  monitoring:
    prometheus_port: 9090
    grafana_port: 3000
    node_exporter_port: 9100
    gpu_exporter_port: 9400
