apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: n8n-network-policy
  namespace: sophia-ai
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgresql
    - podSelector:
        matchLabels:
          app: redis
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress
    ports:
    - port: 5678
      protocol: TCP
  podSelector:
    matchLabels:
      app: n8n-main
  policyTypes:
  - Ingress
  - Egress
