apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sophia-ai-network-policy
  namespace: sophia-ai
spec:
  egress:
  - ports:
    - port: 5432
      protocol: TCP
    - port: 6379
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: postgresql
    - podSelector:
        matchLabels:
          app: redis
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: n8n-main
    - podSelector:
        matchLabels:
          app: nginx-ingress
    ports:
    - port: 8000
      protocol: TCP
  podSelector:
    matchLabels:
      app: sophia-ai
  policyTypes:
  - Ingress
  - Egress
