jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags:
            --allow-insecure-entitlement security.insecure --allow-insecure-entitlement
            network.host
          driver: docker-container
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_USER_NAME }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          build-args: "UV_COMPILE_BYTECODE=1

            UV_LINK_MODE=copy"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./Dockerfile.optimized
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "scoobyjava15/sophia-ai:latest

            scoobyjava15/sophia-ai:${{ github.sha }}"
      - env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        name: Deploy Infrastructure
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: scoobyjava-org/sophia-prod-on-lambda
          work-dir: infrastructure/
      - name: Deploy to Kubernetes
        run: "# Get kubeconfig from Pulumi ESC

          pulumi env open scoobyjava-org/sophia-prod-on-lambda --format env | grep KUBECONFIG
          > kubeconfig.env

          source kubeconfig.env


          # Apply Kubernetes manifests

          kubectl apply -f kubernetes/


          # Wait for deployment

          kubectl rollout status deployment/sophia-ai --timeout=600s

          kubectl rollout status deployment/n8n-main --timeout=600s

          kubectl rollout status deployment/n8n-worker --timeout=600s"
      - name: Verify Deployment
        run: "# Health check endpoints

          curl -f http://${LAMBDA_LABS_INSTANCE_IP}/health

          curl -f http://${LAMBDA_LABS_INSTANCE_IP}:5678/healthz


          # Performance validation

          python scripts/performance_validation.py"
name: Sophia AI Production Deployment
"on":
  push:
    branches:
      - main
  workflow_dispatch: {}
