agent_framework:
  memory_store: postgresql
  primary: langgraph
  tool_registry: dynamic
  workflow_engine: state_machine
context_optimization:
  adaptive_chunking: enabled
  context_compression: enabled
  max_context_tokens: 128000
  relevance_threshold: 0.8
embedding_strategy:
  chunk_size: 512
  multimodal_model: clip-vit-large
  overlap: 50
  reranking: cross-encoder
  text_model: text-embedding-3-large
vector_databases:
  hybrid_search: enabled
  primary: pinecone
  secondary: weaviate
  semantic_caching: redis_vector
