apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qdrant
    deployment: fortress-20250714-112019
  name: qdrant-cluster
  namespace: sophia-ai-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - env:
        - name: QDRANT__SERVICE__HTTP_PORT
          value: '6333'
        - name: QDRANT__SERVICE__GRPC_PORT
          value: '6334'
        image: qdrant/qdrant:v1.7.4
        name: qdrant
        ports:
        - containerPort: 6333
        - containerPort: 6334
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - mountPath: /qdrant/storage
          name: qdrant-storage
      volumes:
      - name: qdrant-storage
        persistentVolumeClaim:
          claimName: qdrant-pvc
