apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-backend-test
  namespace: sophia-ai-prod
  labels:
    app: sophia-backend
    version: containerd-native
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sophia-backend
  template:
    metadata:
      labels:
        app: sophia-backend
    spec:
      # Security: Install as root, then switch to non-root user in command
      containers:
      - name: backend
        image: python:3.11-slim
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "apt-get update && apt-get install -y --no-install-recommends curl && pip install --no-cache-dir fastapi uvicorn && useradd -m -u 1000 appuser && mkdir -p /app-writable && cp /app-source/app.py /app-writable/ && chown -R appuser:appuser /app-writable && su appuser -c 'cd /app-writable && python app.py'"]
        workingDir: /app-writable
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: app-code
          mountPath: /app-source
        - name: app-writable
          mountPath: /app-writable
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: sophia-port-config
              key: BACKEND_PORT
        - name: ENVIRONMENT
          value: "prod"
        - name: PYTHONPATH
          value: "/app"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
            nvidia.com/gpu: "0"
          limits:
            cpu: "1"
            memory: "2Gi"
            nvidia.com/gpu: "0"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      volumes:
      - name: app-code
        configMap:
          name: sophia-app-code
      - name: app-writable
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-backend-test-service
  namespace: sophia-ai-prod
  labels:
    app: sophia-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: sophia-backend 