apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mcp-servers
    component: infrastructure
  name: mcp-servers
  namespace: sophia-ai-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-servers
  template:
    metadata:
      labels:
        app: mcp-servers
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: prod
        - name: MCP_SERVER_TYPE
          value: unified
        image: scoobyjava15/mcp-servers:latest
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        name: mcp-servers
        ports:
        - containerPort: 9000
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
