apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
    component: infrastructure
  name: redis
  namespace: sophia-ai-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - env: []
        image: redis:7-alpine
        livenessProbe: null
        name: redis
        ports:
        - containerPort: 6379
          name: http
        readinessProbe: null
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-pvc
