version: '3.9'

x-default-deploy: &default-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  update_config:
    parallelism: 1
    delay: 10s
    failure_action: rollback
    monitor: 60s
  rollback_config:
    parallelism: 1
    delay: 10s
    failure_action: pause
    monitor: 60s

x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

services:
  # GitHub Integration (Port 9006)
  github-v2:
    image: ${DOCKER_REGISTRY}/sophia-github-v2:${IMAGE_TAG}
    ports:
      - "9006:9006"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9006
      - REDIS_URL=redis://redis:6379
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9006/health"]

  # Slack Integration (Port 9007)
  slack-v2:
    image: ${DOCKER_REGISTRY}/sophia-slack-v2:${IMAGE_TAG}
    ports:
      - "9007:9007"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9007
      - REDIS_URL=redis://redis:6379
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9007/health"]

  # Linear Project Management (Port 9002)
  linear-v2:
    image: ${DOCKER_REGISTRY}/sophia-linear-v2:${IMAGE_TAG}
    ports:
      - "9002:9002"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9002
      - REDIS_URL=redis://redis:6379
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]

  # Notion Knowledge Base (Port 9003)
  notion-v2:
    image: ${DOCKER_REGISTRY}/sophia-notion-v2:${IMAGE_TAG}
    ports:
      - "9003:9003"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9003
      - REDIS_URL=redis://redis:6379
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9003/health"]

  # Codacy Code Quality (Port 9005)
  codacy-v2:
    image: ${DOCKER_REGISTRY}/sophia-codacy-v2:${IMAGE_TAG}
    ports:
      - "9005:9005"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9005
      - REDIS_URL=redis://redis:6379
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9005/health"]

  # Asana Task Management (Port 9004)
  asana-v2:
    image: ${DOCKER_REGISTRY}/sophia-asana-v2:${IMAGE_TAG}
    ports:
      - "9004:9004"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9004
      - REDIS_URL=redis://redis:6379
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9004/health"]

  # HubSpot CRM (Port 9017)
  hubspot:
    image: ${DOCKER_REGISTRY}/sophia-hubspot:${IMAGE_TAG}
    ports:
      - "9017:9017"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9017
      - REDIS_URL=redis://redis:6379
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9017/health"]

  # Playwright Browser Automation (Port 9020)
  playwright:
    image: ${DOCKER_REGISTRY}/sophia-playwright:${IMAGE_TAG}
    ports:
      - "9020:9020"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9020
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 1
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9020/health"]

  # Lambda Labs CLI (Port 9040)
  lambda-labs-cli:
    image: ${DOCKER_REGISTRY}/sophia-lambda-labs-cli:${IMAGE_TAG}
    ports:
      - "9040:9040"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9040
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 1
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9040/health"]

  # UI/UX Agent (Port 9022)
  ui-ux-agent:
    image: ${DOCKER_REGISTRY}/sophia-ui-ux-agent:${IMAGE_TAG}
    ports:
      - "9022:9022"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9022
      - REDIS_URL=redis://redis:6379
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 2
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9022/health"]

  # V0.dev AI UI Generation (Port 9023)
  v0dev:
    image: ${DOCKER_REGISTRY}/sophia-v0dev:${IMAGE_TAG}
    ports:
      - "9023:9023"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9023
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 1
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9023/health"]

  # Figma Context Design-to-Code (Port 9024)
  figma-context:
    image: ${DOCKER_REGISTRY}/sophia-figma-context:${IMAGE_TAG}
    ports:
      - "9024:9024"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - PULUMI_ORG=${PULUMI_ORG:-scoobyjava-org}
      - PORT=9024
    networks:
      - sophia-network
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 1
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9024/health"]

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sophia-private
    deploy:
      <<: *default-deploy
      replicas: 1
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "redis-cli", "ping"]

networks:
  sophia-network:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24

  sophia-public:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24

  sophia-private:
    driver: overlay
    attachable: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24

volumes:
  redis-data:
    driver: local 