version: '3.8'

# Sophia AI Core Instance (GH200 - 192.222.58.232)
# Role: AI/ML Compute Engine & High-Performance Processing

x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-default-resources: &default-resources
  limits:
    memory: 4G
  reservations:
    memory: 2G

x-gpu-resources: &gpu-resources
  limits:
    memory: 8G
  reservations:
    memory: 4G
  generic_resources:
    - discrete_resource_spec:
        kind: "NVIDIA-GPU"
        value: 1

x-default-deploy: &default-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  update_config:
    parallelism: 1
    delay: 10s
    failure_action: rollback
    monitor: 60s
  rollback_config:
    parallelism: 1
    delay: 10s
    failure_action: pause
    monitor: 60s

services:
  # AI Memory V2 - L1 Cache
  ai-memory-v2:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-ai-memory-v2:${IMAGE_TAG:-latest}
    ports:
      - "9000:9000"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=9000
      - REDIS_URL=redis://redis:6379
      - VECTOR_CACHE_SIZE=10000
      - ENABLE_GPU_ACCELERATION=true
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *gpu-resources
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    depends_on:
      - redis
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Lambda GPU AI
  modern_stack-cortex:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-ai-cortex:${IMAGE_TAG:-latest}
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=8081
      - modern_stack_CORTEX_ENABLED=true
      - ENABLE_GPU_ACCELERATION=true
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *gpu-resources
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Mem0 OpenMemory
  mem0-openmemory:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-ai-mem0:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=8080
      - MEMORY_PERSISTENCE_ENABLED=true
      - REDIS_URL=redis://redis:6379
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *default-resources
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    depends_on:
      - redis
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Enhanced Lambda GPU Processing
  modern_stack-cortex-enhanced:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-modern_stack-cortex:${IMAGE_TAG:-latest}
    ports:
      - "8082:8082"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=8082
      - modern_stack_CORTEX_ENHANCED=true
      - ENABLE_GPU_ACCELERATION=true
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *gpu-resources
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # HuggingFace AI Hub
  huggingface-ai:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-huggingface-ai:${IMAGE_TAG:-latest}
    ports:
      - "9012:9012"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=9012
      - HUGGINGFACE_CACHE_DIR=/cache/huggingface
      - ENABLE_GPU_ACCELERATION=true
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *gpu-resources
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    volumes:
      - huggingface-cache:/cache/huggingface
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9012/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Portkey Admin - LLM Gateway
  portkey-admin:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-portkey-admin:${IMAGE_TAG:-latest}
    ports:
      - "9013:9013"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=9013
      - PORTKEY_ADMIN_ENABLED=true
      - REDIS_URL=redis://redis:6379
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *default-resources
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    depends_on:
      - redis
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9013/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prompt Optimizer
  prompt-optimizer:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-prompt-optimizer:${IMAGE_TAG:-latest}
    ports:
      - "9014:9014"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=9014
      - PROMPT_OPTIMIZATION_ENABLED=true
      - ENABLE_GPU_ACCELERATION=true
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *gpu-resources
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9014/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Gong V2 - Sales AI Analysis
  gong-v2:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-gong-v2:${IMAGE_TAG:-latest}
    ports:
      - "9009:9009"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=9009
      - GONG_AI_ANALYSIS_ENABLED=true
      - ENABLE_GPU_ACCELERATION=true
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *gpu-resources
        limits:
          cpus: '3'
          memory: 6G
        reservations:
          cpus: '2'
          memory: 4G
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9009/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Perplexity V2 - AI Research
  perplexity-v2:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-perplexity-v2:${IMAGE_TAG:-latest}
    ports:
      - "9008:9008"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=9008
      - PERPLEXITY_AI_RESEARCH_ENABLED=true
      - ENABLE_GPU_ACCELERATION=true
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *gpu-resources
        limits:
          cpus: '3'
          memory: 6G
        reservations:
          cpus: '2'
          memory: 4G
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9008/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Apollo - Sales Intelligence
  apollo:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-apollo:${IMAGE_TAG:-latest}
    ports:
      - "9015:9015"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=9015
      - APOLLO_SALES_INTELLIGENCE_ENABLED=true
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *default-resources
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9015/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Bright Data - Data Intelligence
  bright-data:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-bright-data:${IMAGE_TAG:-latest}
    ports:
      - "9105:9105"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=9105
      - BRIGHT_DATA_INTELLIGENCE_ENABLED=true
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *default-resources
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9105/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Apify Intelligence - Automation Intelligence
  apify-intelligence:
    image: ${DOCKER_REGISTRY:-scoobyjava15}/sophia-apify-intelligence:${IMAGE_TAG:-latest}
    ports:
      - "9016:9016"
    environment:
      - ENVIRONMENT=prod
      - PULUMI_ORG=scoobyjava-org
      - INSTANCE_NAME=ai-core
      - MCP_SERVER_PORT=9016
      - APIFY_AUTOMATION_INTELLIGENCE_ENABLED=true
    deploy:
      <<: *default-deploy
      replicas: 2
      resources:
        <<: *default-resources
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    networks:
      - sophia-ai-network
      - sophia-public
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9016/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache for AI Services
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 8gb --maxmemory-policy allkeys-lru
    volumes:
      - sophia-ai-redis-data:/data
    deploy:
      <<: *default-deploy
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G
    networks:
      - sophia-ai-network
      - sophia-private
    logging: *default-logging
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Vector Database for AI Processing
  vector-db:
    image: weaviate/weaviate:1.24.0
    ports:
      - "8088:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=false
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=backup-filesystem,text2vec-openai
      - BACKUP_FILESYSTEM_PATH=/var/lib/weaviate/backups
      - CLUSTER_HOSTNAME=weaviate
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      <<: *default-deploy
      replicas: 1
      resources:
        <<: *gpu-resources
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    volumes:
      - weaviate-data:/var/lib/weaviate
    networks:
      - sophia-ai-network
      - sophia-private
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sophia-ai-network:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
  sophia-public:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24
  sophia-private:
    driver: overlay
    attachable: false
    ipam:
      driver: default
      config:
        - subnet: 10.1.3.0/24

volumes:
  sophia-ai-redis-data:
    driver: local
  weaviate-data:
    driver: local
  huggingface-cache:
    driver: local