version: '3.8'

services:
  # etcd cluster for service discovery
  etcd-1:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd-1
    restart: always
    networks:
      - sophia-ai-network
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_NAME=etcd-1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=sophia-ai-cluster
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_QUOTA_BACKEND_BYTES=8589934592  # 8GB
      - ETCD_HEARTBEAT_INTERVAL=250
      - ETCD_ELECTION_TIMEOUT=5000
      - ETCD_MAX_SNAPSHOTS=5
      - ETCD_MAX_WALS=5
      - ETCD_SNAPSHOT_COUNT=10000
      - ETCD_LOG_LEVEL=info
      - ETCD_METRICS=extensive
      - ETCD_ENABLE_V2=false
    volumes:
      - etcd-1-data:/etcd-data
      - ./config/etcd/etcd-1.conf:/etc/etcd/etcd.conf:ro
    command:
      - etcd
      - --config-file=/etc/etcd/etcd.conf
      - --data-dir=/etcd-data
      - --enable-pprof
      - --logger=zap
      - --log-outputs=stderr
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  etcd-2:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd-2
    restart: always
    networks:
      - sophia-ai-network
    ports:
      - "2381:2379"
      - "2382:2380"
    environment:
      - ETCD_NAME=etcd-2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-2:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=sophia-ai-cluster
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_QUOTA_BACKEND_BYTES=8589934592
      - ETCD_HEARTBEAT_INTERVAL=250
      - ETCD_ELECTION_TIMEOUT=5000
      - ETCD_MAX_SNAPSHOTS=5
      - ETCD_MAX_WALS=5
      - ETCD_SNAPSHOT_COUNT=10000
      - ETCD_LOG_LEVEL=info
      - ETCD_METRICS=extensive
      - ETCD_ENABLE_V2=false
    volumes:
      - etcd-2-data:/etcd-data
      - ./config/etcd/etcd-2.conf:/etc/etcd/etcd.conf:ro
    command:
      - etcd
      - --config-file=/etc/etcd/etcd.conf
      - --data-dir=/etcd-data
      - --enable-pprof
      - --logger=zap
      - --log-outputs=stderr
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  etcd-3:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd-3
    restart: always
    networks:
      - sophia-ai-network
    ports:
      - "2383:2379"
      - "2384:2380"
    environment:
      - ETCD_NAME=etcd-3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-3:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=sophia-ai-cluster
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_QUOTA_BACKEND_BYTES=8589934592
      - ETCD_HEARTBEAT_INTERVAL=250
      - ETCD_ELECTION_TIMEOUT=5000
      - ETCD_MAX_SNAPSHOTS=5
      - ETCD_MAX_WALS=5
      - ETCD_SNAPSHOT_COUNT=10000
      - ETCD_LOG_LEVEL=info
      - ETCD_METRICS=extensive
      - ETCD_ENABLE_V2=false
    volumes:
      - etcd-3-data:/etcd-data
      - ./config/etcd/etcd-3.conf:/etc/etcd/etcd.conf:ro
    command:
      - etcd
      - --config-file=/etc/etcd/etcd.conf
      - --data-dir=/etcd-data
      - --enable-pprof
      - --logger=zap
      - --log-outputs=stderr
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # etcd cluster manager UI
  etcd-manager:
    image: deltaprojects/etcdkeeper:latest
    container_name: etcd-manager
    restart: always
    networks:
      - sophia-ai-network
    ports:
      - "8080:8080"
    environment:
      - ETCD_ENDPOINTS=http://etcd-1:2379,http://etcd-2:2379,http://etcd-3:2379
      - ETCD_USERNAME=
      - ETCD_PASSWORD=
      - ETCD_CERT_FILE=
      - ETCD_KEY_FILE=
      - ETCD_CA_FILE=
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # etcd backup service
  etcd-backup:
    image: alpine:latest
    container_name: etcd-backup
    restart: always
    networks:
      - sophia-ai-network
    volumes:
      - etcd-backups:/backups
      - ./scripts/etcd-backup.sh:/backup.sh:ro
    environment:
      - ETCD_ENDPOINTS=http://etcd-1:2379,http://etcd-2:2379,http://etcd-3:2379
      - BACKUP_SCHEDULE=0 2 * * *  # Daily at 2 AM
      - BACKUP_RETENTION_DAYS=7
      - BACKUP_PATH=/backups
    command: >
      sh -c "
        apk add --no-cache curl etcd-ctl dcron &&
        echo '$${BACKUP_SCHEDULE} /backup.sh' > /etc/crontabs/root &&
        crond -f -l 2
      "
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3

  # etcd metrics exporter for Prometheus
  etcd-metrics-exporter:
    image: prom/node-exporter:latest
    container_name: etcd-metrics-exporter
    restart: always
    networks:
      - sophia-ai-network
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
      - '--collector.etcd'
      - '--collector.systemd'
      - '--collector.processes'
    volumes:
      - /:/host:ro,rslave
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3

  # Service registry initializer
  service-registry-init:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: service-registry-init
    networks:
      - sophia-ai-network
    volumes:
      - ./config/etcd/service-registry-init.json:/init-data.json:ro
    environment:
      - ETCDCTL_API=3
      - ETCDCTL_ENDPOINTS=http://etcd-1:2379,http://etcd-2:2379,http://etcd-3:2379
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3
    command: >
      sh -c "
        sleep 30 &&
        etcdctl put /services/unified-project '{
          \"endpoint\": \"http://unified-project:9005\",
          \"capabilities\": [\"project_management\", \"task_tracking\"],
          \"health_check\": \"http://unified-project:9005/health\",
          \"registered_at\": \"$$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
          \"status\": \"active\",
          \"version\": \"3.0.0\"
        }' &&
        etcdctl put /services/prisma-mcp '{
          \"endpoint\": \"http://prisma-mcp:9030\",
          \"capabilities\": [\"schema_introspection\", \"natural_language_migrations\"],
          \"health_check\": \"http://prisma-mcp:9030/health\",
          \"registered_at\": \"$$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
          \"status\": \"active\",
          \"version\": \"6.10.0\"
        }' &&
        etcdctl put /services/unified-memory '{
          \"endpoint\": \"http://unified-memory:9100\",
          \"capabilities\": [\"vector_search\", \"embedding_generation\"],
          \"health_check\": \"http://unified-memory:9100/health\",
          \"registered_at\": \"$$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
          \"status\": \"active\",
          \"version\": \"2.0.0\"
        }' &&
        etcdctl put /config/sophia-ai/deployment '{
          \"environment\": \"production\",
          \"gpu_enabled\": true,
          \"scaling_enabled\": true,
          \"monitoring_enabled\": true,
          \"backup_enabled\": true,
          \"updated_at\": \"$$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
        }' &&
        echo 'Service registry initialized successfully'
      "

  # Service discovery monitor
  service-discovery-monitor:
    build:
      context: .
      dockerfile: docker/Dockerfile.service-discovery-monitor
    container_name: service-discovery-monitor
    restart: always
    networks:
      - sophia-ai-network
    ports:
      - "9090:9090"
    environment:
      - ETCD_ENDPOINTS=http://etcd-1:2379,http://etcd-2:2379,http://etcd-3:2379
      - PROMETHEUS_PORT=9090
      - HEALTH_CHECK_INTERVAL=30
      - SERVICE_TTL=60
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3
    volumes:
      - ./config/etcd/service-discovery-monitor.py:/app/monitor.py:ro
    command: python /app/monitor.py

  # etcd cluster health checker
  etcd-health-checker:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd-health-checker
    restart: always
    networks:
      - sophia-ai-network
    environment:
      - ETCDCTL_API=3
      - ETCDCTL_ENDPOINTS=http://etcd-1:2379,http://etcd-2:2379,http://etcd-3:2379
      - HEALTH_CHECK_INTERVAL=30
      - ALERT_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3
    volumes:
      - ./scripts/etcd-health-check.sh:/health-check.sh:ro
    command: >
      sh -c "
        apk add --no-cache curl &&
        while true; do
          /health-check.sh || echo 'Health check failed' &&
          sleep $${HEALTH_CHECK_INTERVAL}
        done
      "

  # Load balancer for etcd endpoints
  etcd-load-balancer:
    image: nginx:alpine
    container_name: etcd-load-balancer
    restart: always
    networks:
      - sophia-ai-network
    ports:
      - "2378:2378"
    volumes:
      - ./config/etcd/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3
    command: >
      sh -c "
        nginx -g 'daemon off;'
      "

volumes:
  etcd-1-data:
    driver: local
  etcd-2-data:
    driver: local
  etcd-3-data:
    driver: local
  etcd-backups:
    driver: local

networks:
  sophia-ai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 