# Sophia AI Production Deployment Configuration
# This file should be encrypted with Pulumi ESC

deployment:
  environment: production
  version: v2025.7.12
  
domains:
  primary: "YOUR_DOMAIN.com"  # Replace with your domain
  api: "api.YOUR_DOMAIN.com"
  dashboard: "dashboard.YOUR_DOMAIN.com"
  docs: "docs.YOUR_DOMAIN.com"

infrastructure:
  lambda_labs:
    host: "192.222.58.232"
    gpu: "GH200"
    region: "us-west"
    
  kubernetes:
    cluster: "k3s"
    namespace: "sophia-ai-prod"
    
  vercel:
    project: "sophia-ai-dashboard"
    team: "YOUR_TEAM"  # Replace with your Vercel team
    
dns:
  provider: "namecheap"
  records:
    - type: "A"
      name: "@"
      value: "76.76.21.21"  # Vercel IP
    - type: "A"
      name: "www"
      value: "76.76.21.21"  # Vercel IP
    - type: "A"
      name: "api"
      value: "192.222.58.232"  # Lambda Labs
    - type: "CNAME"
      name: "dashboard"
      value: "cname.vercel-dns.com"

services:
  frontend:
    provider: "vercel"
    framework: "nextjs"
    build_command: "npm run build"
    output_directory: ".next"
    
  backend:
    orchestrator:
      replicas: 3
      cpu: "2"
      memory: "4Gi"
    chat:
      replicas: 2
      cpu: "1"
      memory: "2Gi"
    memory:
      replicas: 2
      cpu: "1"
      memory: "2Gi"
      
monitoring:
  prometheus:
    retention: "30d"
    storage: "50Gi"
  grafana:
    admin_user: "admin"
    dashboards:
      - "system-overview"
      - "mcp-health"
      - "cache-performance"

secrets:
  # These will be stored in Pulumi ESC
  namecheap_api_key: "ENCRYPTED"
  namecheap_api_user: "ENCRYPTED"
  vercel_token: "ENCRYPTED"
  openai_api_key: "ENCRYPTED"
  anthropic_api_key: "ENCRYPTED"
  github_token: "ENCRYPTED"
  
backup:
  strategy: "3-2-1"
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention:
    local: 7
    remote: 30
    s3: 90 