values:
  connectors:
    github:
      access_token:
        fn::secret: ${GITHUB_ACCESS_TOKEN}
    hubspot:
      client_id:
        fn::secret: ${HUBSPOT_CLIENT_ID}
      client_secret:
        fn::secret: ${HUBSPOT_CLIENT_SECRET}
      refresh_token:
        fn::secret: ${HUBSPOT_REFRESH_TOKEN}
    slack:
      api_token:
        fn::secret: ${SLACK_API_TOKEN}
  estuary:
    access_token:
      fn::secret: ${ESTUARY_ACCESS_TOKEN}
    refresh_token:
      fn::secret: ${ESTUARY_REFRESH_TOKEN}
    tenant: Pay_Ready
