# Secret Mapping Configuration
# Maps GitHub Organization Secrets to Pulumi ESC paths
# Format: github_secret_name: pulumi_esc_path

# AI/ML Services
OPENAI_API_KEY: values.sophia.ai.openai_api_key
ANTHROPIC_API_KEY: values.sophia.ai.anthropic_api_key
OPENROUTER_API_KEY: values.sophia.ai.openrouter_api_key
PORTKEY_API_KEY: values.sophia.ai.portkey_api_key

# Data Infrastructure
ELIMINATED_ACCOUNT: values.sophia.data.ELIMINATED.account
ELIMINATED_USER: values.sophia.data.ELIMINATED.user
ELIMINATED_PASSWORD: values.sophia.data.ELIMINATED.password
ELIMINATED_WAREHOUSE: values.sophia.data.ELIMINATED.warehouse
ELIMINATED_DATABASE: values.sophia.data.ELIMINATED.database
ELIMINATED_SCHEMA: values.sophia.data.ELIMINATED.schema
ELIMINATED_ROLE: values.sophia.data.ELIMINATED.role

# Vector Databases
QDRANT_API_KEY: values.sophia.data.qdrant_api_key
QDRANT_URL: values.sophia.data.qdrant.url
PINECONE_API_KEY: values.sophia.data.pinecone_api_key

POSTGRES_USER: values.sophia.data.postgres.user
POSTGRES_PASSWORD: values.sophia.data.postgres.password
POSTGRES_DB: values.sophia.data.postgres.database

REDIS_PASSWORD: values.sophia.data.redis.password

# Cloud Infrastructure
LAMBDA_API_KEY: values.sophia.infrastructure.lambda_labs.api_key
LAMBDA_SSH_KEY: values.sophia.infrastructure.lambda_labs.ssh_key
LAMBDA_SSH_PRIVATE_KEY: values.sophia.infrastructure.lambda_labs.ssh_private_key
LAMBDA_API_ENDPOINT: values.sophia.infrastructure.lambda_labs.api_endpoint

DOCKERHUB_USERNAME: values.sophia.infrastructure.docker.username
DOCKER_TOKEN: values.sophia.infrastructure.docker.access_token

AWS_DEPLOY_ROLE_ARN: values.sophia.infrastructure.aws.deploy_role_arn


# Business Intelligence
GONG_ACCESS_KEY: values.sophia.business.gong.access_key
GONG_ACCESS_KEY_SECRET: values.sophia.business.gong.access_key_secret

HUBSPOT_API_KEY: values.sophia.business.hubspot_api_key

# Communication & Collaboration
SLACK_WEBHOOK: values.sophia.communication.slack.webhook_url
SLACK_BOT_TOKEN: values.sophia.communication.slack.bot_token

LINEAR_API_KEY: values.sophia.communication.linear_api_key
ASANA_API_TOKEN: values.sophia.communication.asana_api_token
NOTION_API_KEY: values.sophia.communication.notion_api_key

# Development Tools
GH_API_TOKEN: values.sophia.development.github_token
FIGMA_PAT: values.sophia.development.figma.pat
FIGMA_PROJECT_ID: values.sophia.development.figma.project_id

# Monitoring
GRAFANA_API_KEY: values.sophia.monitoring.grafana.api_key
GRAFANA_URL: values.sophia.monitoring.grafana.url

# Pulumi Self-Reference
PULUMI_ACCESS_TOKEN: values.sophia.infrastructure.pulumi.access_token
