captures:
  sophia/postgresql:
    bindings:
      - resource:
          stream: public.conversations
          syncMode: incremental
        target: sophia/conversations
      - resource:
          stream: public.ai_memory_records
          syncMode: incremental
        target: sophia/ai_memory
      - resource:
          stream: public.business_metrics
          syncMode: incremental
        target: sophia/metrics
    endpoint:
      connector:
        config:
          address: postgresql.sophia-ai.svc.cluster.local:5432
          advanced:
            backfill: false
            sslmode: require
            watermarks: true
          database: sophia_ai
          password: ${POSTGRESQL_ESTUARY_PASSWORD}
          user: estuary_user
        image: ghcr.io/estuary/source-postgres:dev
  sophia/modern_stack:
    bindings:
      - resource:
          table: SOPHIA_AI.PUBLIC.ENRICHED_GONG_CALLS
        target: sophia/gong_calls
      - resource:
          table: SOPHIA_AI.PUBLIC.ENRICHED_HUBSPOT_DEALS
        target: sophia/hubspot_deals
    endpoint:
      connector:
        config:
          account: ${SNOWFLAKE_ACCOUNT}
          database: SOPHIA_AI
          password: ${SNOWFLAKE_PASSWORD}
          schema: PUBLIC
          user: ${SNOWFLAKE_USER}
          warehouse: ${SNOWFLAKE_WAREHOUSE}
        image: ghcr.io/estuary/source-modern_stack:dev
collections:
  sophia/conversations:
    key:
      - /id
    schema:
      properties:
        created_at:
          format: date-time
          type: string
        embedding:
          items:
            type: number
          type: array
        id:
          type: integer
        message:
          type: string
        metadata:
          type: object
      type: object
  sophia/vector_updates:
    key:
      - /embedding_id
    schema:
      properties:
        embedding_id:
          type: string
        metadata:
          type: object
        source:
          type: string
        updated_at:
          format: date-time
          type: string
        vector:
          items:
            type: number
          type: array
      type: object
materializations:
  sophia/pinecone:
    bindings:
      - fields:
          include:
            id: /id
            metadata: /metadata
            vector: /embedding
          recommended: true
        resource:
          index: sophia-conversations
        source: sophia/conversations
    endpoint:
      connector:
        config:
          api_key: ${PINECONE_API_KEY}
          batch_size: 100
          environment: ${PINECONE_ENVIRONMENT}
          flush_interval: 1s
          index_name: sophia-conversations
        image: ghcr.io/estuary/materialize-pinecone:dev
  sophia/weaviate:
    bindings:
      - resource:
          class: SophiaConversation
        source: sophia/conversations
      - resource:
          class: SophiaMemory
        source: sophia/ai_memory
    endpoint:
      connector:
        config:
          api_key: ${WEAVIATE_API_KEY}
          batch_size: 100
          url: ${WEAVIATE_URL}
        image: ghcr.io/estuary/materialize-weaviate:dev
