# MCP VERSION MANAGEMENT CONFIGURATION
# Comprehensive versioning and lifecycle management for Sophia AI's 28 MCP servers

version_policy:
  semantic_versioning: true
  format: "MAJOR.MINOR.PATCH"

  compatibility_matrix:
    major_changes: "Breaking API changes, incompatible updates"
    minor_changes: "New features, backward compatible enhancements"
    patch_changes: "Bug fixes, security updates, documentation"

  deprecation_policy:
    warning_period: "6 months"
    support_period: "12 months"
    migration_support: true
    documentation_required: true
    notification_channels: ["slack", "github_issues", "docs"]

  validation_rules:
    - "All major version changes require migration guide"
    - "Deprecated versions must include replacement instructions"
    - "API changes must maintain backward compatibility for 2 minor versions"
    - "Security patches can break compatibility with documented justification"

# Current MCP Server Version Registry
server_versions:
  # Core Intelligence Servers
  ai_memory:
    current: "2.1.0"
    deprecated: []
    supported: ["2.0.x", "2.1.x"]
    api_version: "v2"
    capabilities: ["semantic_search", "auto_discovery", "context_awareness"]

  sophia_intelligence_unified:
    current: "1.5.2"
    deprecated: ["1.0.x", "1.1.x"]
    supported: ["1.4.x", "1.5.x"]
    api_version: "v1"
    capabilities: ["ai_orchestration", "business_analysis", "data_insights"]

  ELIMINATED_unified:
    current: "3.0.1"
    deprecated: []
    supported: ["2.8.x", "3.0.x"]
    api_version: "v3"
    capabilities: ["sql_execution", "cortex_ai", "data_warehouse"]

  codacy:
    current: "1.3.2"
    deprecated: ["1.0.x", "1.1.x"]
    supported: ["1.2.x", "1.3.x"]
    api_version: "v1"
    capabilities: ["code_analysis", "security_scanning", "quality_metrics"]

  github:
    current: "2.2.0"
    deprecated: []
    supported: ["2.1.x", "2.2.x"]
    api_version: "v2"
    capabilities: ["repository_management", "issue_tracking", "pr_automation"]

  linear:
    current: "1.4.1"
    deprecated: ["1.0.x", "1.1.x"]
    supported: ["1.3.x", "1.4.x"]
    api_version: "v1"
    capabilities: ["project_management", "issue_tracking", "team_analytics"]

  asana:
    current: "1.2.3"
    deprecated: []
    supported: ["1.1.x", "1.2.x"]
    api_version: "v1"
    capabilities: ["task_management", "project_coordination", "team_collaboration"]

  # Business Intelligence Servers
  hubspot_unified:
    current: "2.3.0"
    deprecated: ["1.x.x"]
    supported: ["2.2.x", "2.3.x"]
    api_version: "v2"
    capabilities: ["crm_management", "deal_tracking", "contact_sync"]

  gong:
    current: "1.6.1"
    deprecated: []
    supported: ["1.5.x", "1.6.x"]
    api_version: "v1"
    capabilities: ["call_analysis", "conversation_intelligence", "sales_insights"]

  slack_unified:
    current: "2.1.4"
    deprecated: ["1.x.x"]
    supported: ["2.0.x", "2.1.x"]
    api_version: "v2"
    capabilities: ["messaging", "team_communication", "workflow_automation"]

  notion:
    current: "1.3.0"
    deprecated: []
    supported: ["1.2.x", "1.3.x"]
    api_version: "v1"
    capabilities: ["documentation", "knowledge_management", "collaboration"]

  # Infrastructure Servers
  lambda_labs_cli:
    current: "1.1.2"
    deprecated: []
    supported: ["1.0.x", "1.1.x"]
    api_version: "v1"
    capabilities: ["gpu_management", "instance_control", "resource_optimization"]

  pulumi:
    current: "3.2.1"
    deprecated: ["2.x.x"]
    supported: ["3.1.x", "3.2.x"]
    api_version: "v3"
    capabilities: ["infrastructure_as_code", "deployment_automation", "resource_management"]

  portkey_admin:
    current: "1.0.5"
    deprecated: []
    supported: ["1.0.x"]
    api_version: "v1"
    capabilities: ["ai_gateway", "cost_optimization", "model_routing"]

  # Development Tools
  playwright:
    current: "1.8.0"
    deprecated: []
    supported: ["1.7.x", "1.8.x"]
    api_version: "v1"
    capabilities: ["browser_automation", "testing", "web_scraping"]

  figma_context:
    current: "1.2.1"
    deprecated: []
    supported: ["1.1.x", "1.2.x"]
    api_version: "v1"
    capabilities: ["design_context", "ui_generation", "design_system_sync"]

  ui_ux_agent:
    current: "2.0.3"
    deprecated: ["1.x.x"]
    supported: ["2.0.x"]
    api_version: "v2"
    capabilities: ["ui_generation", "ux_optimization", "component_creation"]

  # Gateway and Orchestration
  mcp_gateway:
    current: "2.4.0"
    deprecated: []
    supported: ["2.3.x", "2.4.x"]
    api_version: "v2"
    capabilities: ["request_routing", "load_balancing", "health_monitoring"]

# Compatibility Matrix
compatibility_matrix:
  # Gateway compatibility with MCP servers
  mcp_gateway:
    "2.4.x":
      compatible_with: ["ai_memory:2.x.x", "codacy:1.3.x", "github:2.x.x"]
      incompatible_with: ["hubspot_unified:1.x.x"]
    "2.3.x":
      compatible_with: ["ai_memory:2.0.x", "codacy:1.2.x", "github:2.1.x"]

  # API version compatibility
  api_versions:
    v1: ["codacy", "linear", "asana", "gong", "notion", "lambda_labs_cli", "portkey_admin", "playwright", "figma_context"]
    v2: ["ai_memory", "github", "hubspot_unified", "slack_unified", "ui_ux_agent", "mcp_gateway"]
    v3: ["ELIMINATED_unified", "pulumi"]

# Migration Paths
migration_paths:
  hubspot_unified:
    from: "1.x.x"
    to: "2.3.0"
    breaking_changes:
      - "Contact API endpoints changed from /contacts to /api/v2/contacts"
      - "Deal webhook payload structure updated"
    migration_steps:
      - "Update client code to use new endpoint paths"
      - "Modify webhook handlers for new payload structure"
      - "Test integration with staging environment"
    estimated_effort: "2-4 hours"

  ui_ux_agent:
    from: "1.x.x"
    to: "2.0.x"
    breaking_changes:
      - "Component generation API redesigned"
      - "New authentication requirements"
    migration_steps:
      - "Implement new authentication flow"
      - "Update component generation calls"
      - "Validate UI generation quality"
    estimated_effort: "4-6 hours"

# Deprecation Schedule
deprecation_schedule:
  "2025-Q1":
    - server: "codacy"
      versions: ["1.0.x", "1.1.x"]
      replacement: "1.3.x"
      reason: "Security vulnerabilities in older versions"

  "2025-Q2":
    - server: "linear"
      versions: ["1.0.x", "1.1.x"]
      replacement: "1.4.x"
      reason: "Performance improvements and new features"

# Validation Configuration
validation:
  automated_checks:
    - "version_format_compliance"
    - "api_compatibility_verification"
    - "migration_guide_completeness"
    - "deprecation_notice_timing"

  manual_reviews:
    - "breaking_change_justification"
    - "migration_effort_estimation"
    - "business_impact_assessment"
    - "security_review_for_major_changes"

# Monitoring and Alerting
monitoring:
  version_drift_detection: true
  compatibility_monitoring: true
  deprecation_alerts:
    advance_warning: "90 days"
    final_warning: "30 days"
    channels: ["slack://sophia-dev", "github://issues"]

  performance_tracking:
    - "version_upgrade_success_rate"
    - "rollback_frequency"
    - "migration_completion_time"
