# Sophia AI Unified MCP Configuration
# SINGLE SOURCE OF TRUTH for all MCP servers
# Date: July 9, 2025

version: "5.0"
last_updated: "2025-07-09"
environment: "prod"

# Deployment information
deployment:
  host: "104.171.202.117"  # Lambda Labs
  platform: "kubernetes"
  namespace: "sophia-mcp"
  registry: "docker.io/scoobyjava15"

# Official port allocations - NO CONFLICTS
mcp_servers:
  tier_1_primary:
    ai_memory:
      port: 9000
      status: active
      capabilities: [MEMORY, EMBEDDING, SEARCH, ANALYTICS]
      owner: core_team
      version: "2.1.0"
      resources:
        memory: 4Gi
        cpu: 2000m
        replicas: 2
      
    modern_stack_unified:
      port: 9001
      status: active
      capabilities: [ANALYTICS, EMBEDDING, SEARCH, COMPLETION]
      owner: data_team
      version: "3.0.1"
      resources:
        memory: 4Gi
        cpu: 2000m
        replicas: 2
      
    gong_v2:
      port: 9002
      status: active
      capabilities: [CALLS, TRANSCRIPTS, ANALYTICS]
      owner: sales_team
      version: "1.6.1"
      resources:
        memory: 2Gi
        cpu: 1000m
        replicas: 2
      
    hubspot_unified:
      port: 9003
      status: active
      capabilities: [CRM, CONTACTS, DEALS, ANALYTICS]
      owner: sales_team
      version: "2.3.0"
      resources:
        memory: 2Gi
        cpu: 1000m
        replicas: 2
      
    slack_v2:
      port: 9004
      status: active
      capabilities: [MESSAGING, CHANNELS, USERS, SEARCH]
      owner: ops_team
      version: "1.5.0"
      resources:
        memory: 2Gi
        cpu: 1000m
        replicas: 2

  tier_2_secondary:
    github_v2:
      port: 9005
      status: active
      capabilities: [REPOS, ISSUES, PRS, ACTIONS]
      owner: dev_team
      version: "2.2.0"
      resources:
        memory: 2Gi
        cpu: 1000m
        replicas: 1
      
    linear_v2:
      port: 9006
      status: active
      capabilities: [PROJECTS, ISSUES, TEAMS, ANALYTICS]
      owner: dev_team
      version: "1.4.1"
      resources:
        memory: 2Gi
        cpu: 1000m
        replicas: 1
      
    asana_v2:
      port: 9007
      status: active
      capabilities: [PROJECTS, TASKS, TEAMS]
      owner: product_team
      version: "1.2.3"
      resources:
        memory: 2Gi
        cpu: 1000m
        replicas: 1
      
    notion_v2:
      port: 9008
      status: active
      capabilities: [DOCS, KNOWLEDGE_BASE, SEARCH]
      owner: product_team
      version: "1.3.0"
      resources:
        memory: 2Gi
        cpu: 1000m
        replicas: 1
      
    codacy:
      port: 3008
      status: active
      capabilities: [CODE_ANALYSIS, SECURITY, METRICS]
      owner: dev_team
      version: "2.0.0"
      resources:
        memory: 2Gi
        cpu: 1000m
        replicas: 1

    portkey_admin:
      port: 9013
      status: active
      capabilities: [LLM_ROUTING, COST_TRACKING, ANALYTICS]
      owner: infra_team
      version: "1.0.0"
      resources:
        memory: 1Gi
        cpu: 500m
        replicas: 1

    postgres:
      port: 9009
      status: active
      capabilities: [SQL, ANALYTICS, STORAGE]
      owner: data_team
      version: "15.3"
      resources:
        memory: 4Gi
        cpu: 2000m
        replicas: 1

  tier_3_tertiary:
    figma_context:
      port: 9010
      status: experimental
      capabilities: [DESIGN, WORKFLOW, ANALYTICS]
      owner: design_team
      version: "1.0.0"
      resources:
        memory: 1Gi
        cpu: 500m
        replicas: 1
      
    lambda_labs_cli:
      port: 9011
      status: active
      capabilities: [INFRASTRUCTURE, ANALYTICS]
      owner: infra_team
      version: "1.1.0"
      resources:
        memory: 1Gi
        cpu: 500m
        replicas: 1
      
    ui_ux_agent:
      port: 9012
      status: experimental
      capabilities: [UI_GENERATION, CODE_ANALYSIS]
      owner: design_team
      version: "1.0.0"
      resources:
        memory: 2Gi
        cpu: 1000m
        replicas: 1

    openrouter_search:
      port: 9014
      status: experimental
      capabilities: [LLM_ACCESS, MODEL_SELECTION]
      owner: infra_team
      version: "1.0.0"
      resources:
        memory: 1Gi
        cpu: 500m
        replicas: 1

# Central services
central_services:
  mcp_orchestration:
    port: 8080
    description: "Central MCP orchestration and routing"
    owner: core_team
    
  registry_v2:
    port: 8081
    description: "MCP server registry and discovery"
    owner: core_team
    
  health_monitor:
    port: 8082
    description: "Unified health monitoring service"
    owner: ops_team

# Deprecated servers - DO NOT USE
deprecated_servers:
  - name: pinecone_server
    reason: "Replaced by Lambda GPU in UnifiedMemoryService"
    removal_date: "2025-08-01"
    migration_guide: "Use UnifiedMemoryService.search_knowledge() instead"
    
  - name: weaviate_server
    reason: "Replaced by Lambda GPU in UnifiedMemoryService"
    removal_date: "2025-08-01"
    migration_guide: "Use UnifiedMemoryService.search_knowledge() instead"
    
  - name: unified_chat_service
    reason: "Replaced by SophiaUnifiedOrchestrator"
    removal_date: "2025-08-01"
    migration_guide: "Use backend.services.sophia_unified_orchestrator.SophiaUnifiedOrchestrator"
    
  - name: sophia_ai_orchestrator
    reason: "Replaced by SophiaUnifiedOrchestrator"
    removal_date: "2025-08-01"
    migration_guide: "Use backend.services.sophia_unified_orchestrator.SophiaUnifiedOrchestrator"

# Health check configuration
health_check:
  interval: 30
  timeout: 10
  retry_attempts: 3
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60

# Monitoring configuration
monitoring:
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: true
    port: 3000
  
# Port allocation policy
port_allocation:
  tier_1_range: "9000-9099"
  tier_2_range: "9100-9199"  
  tier_3_range: "9200-9299"
  central_services: "8000-8099"
  development: "3000-3099"

# Capability definitions
capability_definitions:
  MEMORY: "Persistent memory storage and retrieval"
  EMBEDDING: "Vector embedding generation"
  SEARCH: "Semantic and keyword search"
  ANALYTICS: "Data analysis and reporting"
  CRM: "Customer relationship management"
  CALLS: "Call recording and analysis"
  MESSAGING: "Team communication"
  CODE_ANALYSIS: "Code quality and security analysis"
  INFRASTRUCTURE: "Infrastructure management"
  DEPLOYMENT: "Application deployment"
  MONITORING: "System monitoring"
  WORKFLOW: "Task and project management"
  UI_GENERATION: "UI component generation"
  LLM_ROUTING: "Language model routing"
  COST_TRACKING: "Cost monitoring and optimization" 