# 🚀 Sophia AI Strategic Integration Configuration
# Comprehensive configuration for all five strategic components
# Date: January 15, 2025

version: "1.0"
deployment_id: "strategic_integration_2025"
environment: "production"

# =============================================================================
# COMPONENT 1: PORTKEY/OPENROUTER DYNAMIC ROUTING SYSTEM
# =============================================================================
portkey_router:
  enabled: true
  service_name: "enhanced_intelligent_router"
  port: 9100
  
  # Model Configuration
  models:
    claude-4-sonnet:
      tier: "premium"
      quality_score: 95
      latency_p95: 800
      cost_per_1k: 0.003
      freshness_days: 30
      use_cases: ["reasoning", "analysis", "coding"]
      max_tokens: 200000
      
    gemini-2.5-flash:
      tier: "fast"
      quality_score: 85
      latency_p95: 300
      cost_per_1k: 0.0001
      freshness_days: 45
      use_cases: ["fast_response", "simple_queries"]
      max_tokens: 32000
      
    grok-4:
      tier: "premium"
      quality_score: 92
      latency_p95: 900
      cost_per_1k: 0.004
      freshness_days: 15
      use_cases: ["reasoning", "real_time", "analysis"]
      max_tokens: 128000
  
  # Performance Targets
  performance:
    routing_latency_p95: 180  # milliseconds
    model_selection_accuracy: 90  # percentage
    cost_per_query_max: 0.05  # dollars
    success_rate_min: 99.5  # percentage
  
  # Cost Optimization
  cost_optimization:
    daily_budget: 100.0  # dollars
    request_budget_max: 0.05  # dollars per request
    fallback_to_cheaper: true
    cache_responses: true
    
  # Scoring Weights
  scoring_weights:
    quality: 0.25
    latency: 0.25
    cost: 0.2
    freshness: 0.1
    use_case_match_bonus: 0.1

# =============================================================================
# COMPONENT 2: ENHANCED DASHBOARD SYSTEM
# =============================================================================
enhanced_dashboard:
  enabled: true
  service_name: "adaptive_dashboard"
  port: 3000
  
  # Theme Configuration
  themes:
    dark:
      primary: "#3B82F6"
      secondary: "#8B5CF6"
      background: "#111827"
      gradient: "linear-gradient(135deg, #1f2937 0%, #374151 100%)"
      
    light:
      primary: "#2563EB"
      secondary: "#7C3AED"
      background: "#FFFFFF"
      gradient: "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)"
      
    cyberpunk:
      primary: "#00D2FF"
      secondary: "#FF0080"
      background: "#0A0A0A"
      gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"
      accent: "#00FF88"
  
  # Personality Modes
  personality_modes:
    professional:
      tone: "formal"
      response_style: "detailed"
      ui_complexity: "standard"
      
    snarky:
      tone: "casual"
      response_style: "witty"
      ui_complexity: "simplified"
      
    analytical:
      tone: "technical"
      response_style: "data_driven"
      ui_complexity: "advanced"
      
    creative:
      tone: "inspirational"
      response_style: "visual"
      ui_complexity: "artistic"
  
  # Interaction Styles
  interaction_styles:
    executive:
      kpi_cards: { cols: 4, priority: "high" }
      charts: { cols: 2, priority: "medium" }
      details: { cols: 1, priority: "low" }
      
    analytical:
      charts: { cols: 3, priority: "high" }
      kpi_cards: { cols: 2, priority: "medium" }
      details: { cols: 2, priority: "high" }
      
    overview:
      kpi_cards: { cols: 3, priority: "medium" }
      charts: { cols: 2, priority: "medium" }
      details: { cols: 1, priority: "medium" }
  
  # Performance Targets
  performance:
    load_time_max: 2000  # milliseconds
    interactive_response_max: 200  # milliseconds
    theme_adaptation_max: 500  # milliseconds
    nlp_query_accuracy_min: 95  # percentage

# =============================================================================
# COMPONENT 3: MCP SERVER CONSOLIDATION
# =============================================================================
mcp_consolidation:
  enabled: true
  
  # Unified Dynamic Router
  unified_router:
    service_name: "unified_dynamic_mcp_router"
    port: 9101
    capabilities: ["ROUTING", "ORCHESTRATION", "ANALYTICS"]
    tier: "PRIMARY"
  
  # Service Registry
  service_registry:
    project_management:
      linear: { port: 9006, capabilities: ["PROJECT_MANAGEMENT", "ISSUE_TRACKING"] }
      asana: { port: 9007, capabilities: ["TASK_MANAGEMENT", "WORKFLOW"] }
      notion: { port: 9008, capabilities: ["KNOWLEDGE_BASE", "DOCUMENTATION"] }
      github: { port: 9005, capabilities: ["CODE_MANAGEMENT", "WORKFLOW"] }
      
    data_operations:
      ELIMINATED: { port: 9001, capabilities: ["ANALYTICS", "EMBEDDING", "SEARCH"] }
      postgres: { port: 9012, capabilities: ["DATABASE", "SQL", "ANALYTICS"] }
      redis: { port: 6379, capabilities: ["CACHE", "SESSION", "REALTIME"] }
      
    communication:
      slack: { port: 9004, capabilities: ["MESSAGING", "NOTIFICATIONS"] }
      hubspot: { port: 9003, capabilities: ["CRM", "CONTACTS", "DEALS"] }
      gong: { port: 9002, capabilities: ["CALLS", "TRANSCRIPTS", "ANALYTICS"] }
      
    ai_services:
      ai_memory: { port: 9000, capabilities: ["MEMORY", "EMBEDDING", "SEARCH"] }
      portkey: { port: 9100, capabilities: ["LLM_ROUTING", "COST_OPTIMIZATION"] }
      openrouter: { port: 9015, capabilities: ["MODEL_SEARCH", "COMPARISON"] }
  
  # Finance Intelligence Server
  finance_intelligence:
    service_name: "finance_intelligence_mcp"
    port: 9102
    capabilities: ["FRAUD_DETECTION", "REVENUE_FORECASTING", "RISK_ANALYSIS"]
    
    # Fraud Detection Configuration
    fraud_detection:
      threshold: 0.7
      alert_channel: "#fraud-alerts"
      models: ["grok-4"]
      data_sources: ["hubspot", "gong"]
      
    # Revenue Forecasting
    revenue_forecasting:
      schedule: "0 9 * * *"  # Daily at 9 AM
      models: ["claude-4"]
      confidence_intervals: true
      scenario_modeling: ["best", "worst", "likely"]
  
  # Consolidation Targets
  consolidation:
    target_reduction: 30  # percentage
    current_servers: 17
    target_servers: 12
    efficiency_gain: 25  # percentage

# =============================================================================
# COMPONENT 4: N8N & ESTUARY INTEGRATION
# =============================================================================
n8n_integration:
  enabled: true
  
  # AI-Powered N8N Orchestrator
  orchestrator:
    service_name: "intelligent_n8n_orchestrator"
    port: 8080
    ai_model: "claude-4"
    
  # Workflow Templates
  workflow_templates:
    daily_business_intelligence:
      name: "Daily Business Intelligence"
      schedule: "0 9 * * *"
      nodes:
        - name: "Trigger"
          type: "schedule"
        - name: "Fetch Modern Stack Data"
          type: "ELIMINATED"
        - name: "AI Analysis"
          type: "ai_processing"
          model: "claude-4"
        - name: "Send to Slack"
          type: "slack"
          channel: "#executive-updates"
          
    customer_health_monitoring:
      name: "Customer Health Monitoring"
      trigger: "gong_call_completed"
      nodes:
        - name: "Analyze Call Sentiment"
          type: "ai_processing"
          model: "gemini-2.5"
        - name: "Check HubSpot Deal Status"
          type: "hubspot"
        - name: "Calculate Health Score"
          type: "calculation"
        - name: "Conditional Alert"
          type: "conditional"
          condition: "health_score < 70"
  
  # Estuary Integration
  estuary:
    flows:
      hubspot_to_ELIMINATED:
        source: "hubspot"
        destination: "ELIMINATED"
        webhook: "https://sophia-ai.com/webhooks/n8n/deal-created"
        
      gong_to_ELIMINATED:
        source: "gong"
        destination: "ELIMINATED"
        webhook: "https://sophia-ai.com/webhooks/n8n/call-completed"
        
      slack_to_ELIMINATED:
        source: "slack"
        destination: "ELIMINATED"
        webhook: "https://sophia-ai.com/webhooks/n8n/message-alert"
  
  # Performance Targets
  performance:
    workflow_creation_time: 600  # seconds (10 minutes)
    execution_success_rate: 95  # percentage
    average_execution_time: 30  # seconds
    prediction_accuracy: 80  # percentage

# =============================================================================
# COMPONENT 5: LANGGRAPH AGENT BUILDER
# =============================================================================
agent_builder:
  enabled: true
  
  # Natural Language Agent Factory
  agent_factory:
    service_name: "langgraph_agent_factory"
    port: 9103
    ai_model: "claude-4"
    
  # Agent Templates
  agent_templates:
    crm_fraud_detection:
      name: "CRM Fraud Detection Agent"
      description: "Monitors HubSpot deals and analyzes Gong calls for fraud patterns"
      workflow:
        nodes:
          - id: "deal_monitor"
            type: "mcp_tool"
            mcp_server: "hubspot"
            tool_name: "monitor_deals"
          - id: "call_analysis"
            type: "mcp_tool"
            mcp_server: "gong"
            tool_name: "analyze_calls"
          - id: "fraud_scoring"
            type: "ai_processing"
            model: "grok-4"
          - id: "alert_system"
            type: "mcp_tool"
            mcp_server: "slack"
            tool_name: "send_alert"
            
    revenue_forecasting:
      name: "Revenue Forecasting Agent"
      description: "Automated revenue forecasting with multi-source data analysis"
      workflow:
        nodes:
          - id: "data_collection"
            type: "parallel"
            sub_nodes: ["hubspot_data", "gong_data", "ELIMINATED_data"]
          - id: "forecast_generation"
            type: "ai_processing"
            model: "claude-4"
          - id: "report_generation"
            type: "mcp_tool"
            mcp_server: "report_generator"
  
  # Testing Framework
  testing:
    sandbox_environment: true
    automated_testing: true
    performance_benchmarking: true
    security_scanning: true
    
  # Deployment Pipeline
  deployment:
    automated_deployment: true
    kubernetes_integration: true
    monitoring_setup: true
    rollback_capability: true
  
  # Performance Targets
  performance:
    agent_creation_time: 600  # seconds (10 minutes)
    deployment_success_rate: 95  # percentage
    test_coverage: 80  # percentage
    user_satisfaction: 90  # percentage

# =============================================================================
# CROSS-COMPONENT INTEGRATION
# =============================================================================
integration:
  # State Management
  state_management:
    central_state_manager: true
    real_time_sync: true
    conflict_resolution: true
    
  # Data Flow
  data_flow:
    user_request_flow:
      - dashboard
      - router
      - mcp_services
      - n8n_workflows
      - agent_builder
      
    metrics_flow:
      - router_metrics
      - dashboard_updates
      - mcp_health
      - workflow_status
      - agent_performance
  
  # Communication Protocols
  communication:
    websocket_enabled: true
    rest_api_enabled: true
    mcp_protocol_enabled: true
    event_driven_architecture: true
  
  # Monitoring & Observability
  monitoring:
    prometheus_metrics: true
    grafana_dashboards: true
    distributed_tracing: true
    log_aggregation: true
    alert_management: true

# =============================================================================
# DEPLOYMENT CONFIGURATION
# =============================================================================
deployment:
  # Infrastructure
  infrastructure:
    lambda_labs:
      primary_server: "192.222.58.232"
      mcp_server: "104.171.202.117"
      data_server: "104.171.202.134"
      
  # Kubernetes
  kubernetes:
    namespace: "sophia-strategic"
    replicas:
      router: 2
      dashboard: 3
      mcp_servers: 1
      n8n: 2
      agent_builder: 1
      
  # Security
  security:
    pulumi_esc_integration: true
    secret_management: "github_org_secrets"
    ssl_enabled: true
    rbac_enabled: true
    
  # Performance
  performance:
    auto_scaling: true
    load_balancing: true
    caching: true
    cdn_enabled: true

# =============================================================================
# SUCCESS METRICS
# =============================================================================
success_metrics:
  technical:
    system_latency_p95: 180  # milliseconds
    component_integration: 100  # percentage
    resource_efficiency: 30  # percentage reduction
    deployment_speed: 60  # percentage faster
    
  business:
    developer_productivity: 70  # percentage increase
    cost_optimization: 40  # percentage reduction
    user_satisfaction: 95  # percentage
    platform_adoption: 90  # percentage
    
  operational:
    system_reliability: 99.9  # percentage uptime
    error_rate: 0.1  # percentage
    monitoring_coverage: 100  # percentage
    security_compliance: 100  # percentage

# =============================================================================
# FEATURE FLAGS
# =============================================================================
feature_flags:
  enable_portkey_router: true
  enable_enhanced_dashboard: true
  enable_mcp_consolidation: true
  enable_n8n_integration: true
  enable_agent_builder: true
  enable_cross_component_sync: true
  enable_advanced_monitoring: true
  enable_cost_optimization: true
  enable_security_scanning: true
  enable_performance_profiling: true 