apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-{{SERVER_NAME}}
  namespace: sophia-ai-prod
  labels:
    app: mcp-{{SERVER_NAME}}
    component: mcp-server
    server: {{SERVER_NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-{{SERVER_NAME}}
  template:
    metadata:
      labels:
        app: mcp-{{SERVER_NAME}}
        component: mcp-server
        server: {{SERVER_NAME}}
    spec:
      containers:
      - name: mcp-{{SERVER_NAME}}
        image: scoobyjava15/sophia-mcp-{{SERVER_NAME}}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: {{PORT}}
          name: http
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: PULUMI_ORG
          value: "scoobyjava-org"
        - name: MCP_SERVER_NAME
          value: "{{SERVER_NAME}}"
        - name: MCP_SERVER_PORT
          value: "{{PORT}}"
        livenessProbe:
          httpGet:
            path: /health
            port: {{PORT}}
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{PORT}}
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 