apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-snowflake
  namespace: sophia-ai-prod
  labels:
    app: mcp-snowflake
    component: mcp-server
    server: snowflake
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-snowflake
  template:
    metadata:
      labels:
        app: mcp-snowflake
        component: mcp-server
        server: snowflake
    spec:
      nodeSelector:
        kubernetes.io/hostname: sophia-mcp-orchestrator
      containers:
      - name: mcp-snowflake
        image: scoobyjava15/sophia-mcp-snowflake:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9002
          name: http
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: PULUMI_ORG
          value: "scoobyjava-org"
        - name: MCP_SERVER_NAME
          value: "snowflake"
        - name: MCP_SERVER_PORT
          value: "9002"
        livenessProbe:
          httpGet:
            path: /health
            port: 9002
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 