apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-codacy
  namespace: sophia-ai-prod
  labels:
    app: mcp-codacy
    component: mcp-server
    server: codacy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-codacy
  template:
    metadata:
      labels:
        app: mcp-codacy
        component: mcp-server
        server: codacy
    spec:
      containers:
      - name: mcp-codacy
        image: scoobyjava15/sophia-mcp-codacy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9006
          name: http
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: PULUMI_ORG
          value: "scoobyjava-org"
        - name: MCP_SERVER_NAME
          value: "codacy"
        - name: MCP_SERVER_PORT
          value: "9006"
        livenessProbe:
          httpGet:
            path: /health
            port: 9006
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9006
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 