apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-gong
  namespace: sophia-ai-prod
  labels:
    app: mcp-gong
    component: mcp-server
    server: gong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-gong
  template:
    metadata:
      labels:
        app: mcp-gong
        component: mcp-server
        server: gong
    spec:
      containers:
      - name: mcp-gong
        image: scoobyjava15/sophia-mcp-gong:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: http
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: PULUMI_ORG
          value: "scoobyjava-org"
        - name: MCP_SERVER_NAME
          value: "gong"
        - name: MCP_SERVER_PORT
          value: "9001"
        livenessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 