apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sophia-backend
    component: api
    environment: production
  name: sophia-backend
  namespace: sophia-ai-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sophia-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      labels:
        app: sophia-backend
        component: api
    spec:
      containers:
        - env:
            - name: SOPHIA_ENVIRONMENT
              value: production
            - name: SOPHIA_PORT
              value: "8000"
            - name: PULUMI_ORG
              value: scoobyjava-org
          image: scoobyjava15/sophia-backend:latest
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: sophia-backend
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/ready
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 2Gi
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: sophia-backend-sa
