version: '3.9'

services:
  ai_memory_v2:
    image: scoobyjava15/ai-memory-v2:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    environment:
      AI_MEMORY_V2_PORT: 9001
      AI_MEMORY_V2_LOG_LEVEL: INFO
      AI_MEMORY_V2_DB_DSN: postgresql+asyncpg://ai_memory:${DB_PASSWORD}@postgres:5432/ai_memory
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AI_MEMORY_V2_ENABLE_METRICS: "true"
      PULUMI_ORG: scoobyjava-org
      ENVIRONMENT: production
    ports:
      - "9001:9001"
    networks:
      - sophia-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: pgvector/pgvector:pg16
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    environment:
      POSTGRES_USER: ai_memory
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ai_memory
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ai_memory_db_data:/var/lib/postgresql/data
    networks:
      - sophia-ai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_memory"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    deploy:
      replicas: 1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sophia-ai.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - sophia-ai-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  sophia-ai-network:
    external: true

volumes:
  ai_memory_db_data:
    driver: local
  pgadmin_data:
    driver: local

secrets:
  db_password:
    external: true
  openai_api_key:
    external: true
