apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcp-servers
  name: mcp-servers
  namespace: sophia-ai-prod
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mcp-servers
  type: ClusterIP
