apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: sophia-ai-prod
spec:
  ports:
  - name: http
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
