apiVersion: v1
kind: Service
metadata:
  labels:
    app: sophia-api
  name: sophia-api
  namespace: sophia-ai-prod
spec:
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: sophia-api
  type: ClusterIP
