{{- range $serverName, $server := .Values.servers }}
{{- if $server.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $server.name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    app: sophia-mcp
    component: {{ $server.name }}
    tier: {{ $server.tier }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ $server.port }}
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: sophia-mcp
    component: {{ $server.name }}
{{- end }}
{{- end }}

{{- range $serviceName, $service := .Values.centralServices }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    app: sophia-mcp
    component: {{ $service.name }}
    type: central-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ $service.port }}
    targetPort: http
    protocol: TCP
  selector:
    app: sophia-mcp
    component: {{ $service.name }}
{{- end }}
{{- end }} 