---
# Phase 6: ArgoCD GitOps Application
# Automated deployment with sync policies
# Date: July 12, 2025

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sophia-ai-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ai-cherry/sophia-main
    targetRevision: main
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: sophia-ai-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10

---
# MCP Servers Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sophia-mcp-servers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ai-cherry/sophia-main
    targetRevision: main
    path: k8s/mcp-servers
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp-servers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
# Monitoring Stack Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sophia-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: HEAD
    chart: kube-prometheus-stack
    helm:
      releaseName: prometheus
      values: |
        prometheus:
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
        grafana:
          adminPassword: sophia-admin-2025
          ingress:
            enabled: true
            hosts:
              - grafana.sophia-ai.com
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'sophia-dashboards'
                orgId: 1
                folder: 'Sophia AI'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/sophia
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
# Data Services Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sophia-data-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ai-cherry/sophia-main
    targetRevision: feature/full-prod-beast
    path: k8s/data-services
  destination:
    server: https://kubernetes.default.svc
    namespace: sophia-ai-prod
  syncPolicy:
    automated:
      prune: false  # Don't auto-prune stateful services
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 