name: Codebase Context Ingestion

on:
  push:
    branches: [ main ]

jobs:
  ingest-codebase:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # We will add openai, pinecone-client, etc. here later
          pip install -r requirements.txt || pip install -r docker-requirements.txt || echo "No requirements file found, proceeding without."


      - name: Run Ingestion Script
        run: python scripts/ingest_codebase.py
        env:
          PINECONE_API_KEY: \${{ secrets.PINECONE_API_KEY }}
          OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}
          PINECONE_ENVIRONMENT: \${{ secrets.PINECONE_ENVIRONMENT }}
