global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sophia-ai-prod'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

scrape_configs:
  # Docker Swarm nodes
  - job_name: 'docker-nodes'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: node
      - source_labels: [__meta_dockerswarm_node_platform_architecture]
        target_label: arch
      - source_labels: [__meta_dockerswarm_node_manager_status]
        target_label: manager_status

  # Docker Swarm services
  - job_name: 'docker-services'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: services
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: service
      - source_labels: [__meta_dockerswarm_service_mode]
        target_label: mode
      - source_labels: [__meta_dockerswarm_service_label_prometheus_scrape]
        regex: "true"
        action: keep

  # Docker Swarm tasks (containers)
  - job_name: 'docker-tasks'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: service
      - source_labels: [__meta_dockerswarm_task_container_id]
        target_label: container_id
      - source_labels: [__meta_dockerswarm_task_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_service_label_prometheus_scrape]
        regex: "true"
        action: keep
      - source_labels: [__meta_dockerswarm_service_label_prometheus_port]
        target_label: __address__
        replacement: $1
      - source_labels: [__meta_dockerswarm_service_label_prometheus_path]
        target_label: __metrics_path__
        regex: (.+)

  # Sophia Backend metrics
  - job_name: 'sophia-backend'
    static_configs:
      - targets: ['sophia-backend:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'sophia-backend'

  # MCP Servers metrics
  - job_name: 'mcp-servers'
    static_configs:
      - targets:
          - 'mem0-server:8080'
          - 'cortex-aisql-server:8080'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):.*'
        target_label: mcp_server
        replacement: '$1'

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  # PostgreSQL exporter (if deployed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter (if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
