-- =====================================================================
-- AI_WEB_RESEARCH Schema - Third-Party Intelligence
-- =====================================================================

USE DATABASE SOPHIA_AI;
CREATE SCHEMA IF NOT EXISTS AI_WEB_RESEARCH;
USE SCHEMA AI_WEB_RESEARCH;

-- Industry trends and intelligence
CREATE TABLE IF NOT EXISTS INDUSTRY_TRENDS (
    TREND_ID VARCHAR(255) PRIMARY KEY,
    TREND_TITLE VARCHAR(500) NOT NULL,
    TREND_DESCRIPTION VARCHAR(4000),
    
    -- Classification
    INDUSTRY_SECTOR VARCHAR(255),
    TREND_CATEGORY VARCHAR(255),
    TREND_TYPE VARCHAR(100),
    
    -- Relevance and impact
    RELEVANCE_SCORE FLOAT,
    BUSINESS_IMPACT_SCORE FLOAT,
    URGENCY_LEVEL VARCHAR(50),
    
    -- Source information
    SOURCE_URL VARCHAR(2000),
    SOURCE_DOMAIN VARCHAR(255),
    SOURCE_TYPE VARCHAR(100),
    SOURCE_CREDIBILITY_SCORE FLOAT,
    PUBLICATION_DATE DATE,
    
    -- AI processing
    AI_INFERRED_TAGS VARIANT,
    SENTIMENT_SCORE FLOAT,
    ENTITY_MENTIONS VARIANT,
    KEY_INSIGHTS VARIANT,
    
    -- Competitive intelligence
    COMPETITORS_MENTIONED VARIANT,
    COMPETITIVE_IMPLICATIONS VARCHAR(2000),
    
    -- AI Memory integration
    AI_MEMORY_EMBEDDING VECTOR(FLOAT, 768),
    AI_MEMORY_METADATA VARCHAR(16777216),
    AI_MEMORY_UPDATED_AT TIMESTAMP_NTZ,
    
    -- Metadata layer
    LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFIDENCE_SCORE FLOAT DEFAULT 0.8,
    DATA_SOURCE VARCHAR(100) DEFAULT 'WEB_RESEARCH',
    
    -- Audit trail
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    DISCOVERED_BY VARCHAR(255)
);

-- Competitor updates and intelligence
CREATE TABLE IF NOT EXISTS COMPETITOR_INTELLIGENCE (
    INTELLIGENCE_ID VARCHAR(255) PRIMARY KEY,
    COMPETITOR_NAME VARCHAR(255) NOT NULL,
    
    -- Intelligence details
    INTELLIGENCE_TYPE VARCHAR(100),
    INTELLIGENCE_SUMMARY VARCHAR(2000),
    DETAILED_ANALYSIS VARCHAR(8000),
    
    -- Source and verification
    SOURCE_URL VARCHAR(2000),
    SOURCE_TYPE VARCHAR(100),
    VERIFICATION_STATUS VARCHAR(50),
    COLLECTION_DATE DATE,
    
    -- Business implications
    THREAT_LEVEL VARCHAR(50),
    OPPORTUNITY_LEVEL VARCHAR(50),
    RECOMMENDED_ACTIONS VARIANT,
    
    -- AI processing
    AI_ANALYSIS_SUMMARY VARCHAR(4000),
    STRATEGIC_IMPLICATIONS VARIANT,
    
    -- Metadata layer
    LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFIDENCE_SCORE FLOAT DEFAULT 0.7,
    DATA_SOURCE VARCHAR(100) DEFAULT 'WEB_RESEARCH',
    
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Partnership opportunities
CREATE TABLE IF NOT EXISTS PARTNERSHIP_OPPORTUNITIES (
    OPPORTUNITY_ID VARCHAR(255) PRIMARY KEY,
    PARTNER_NAME VARCHAR(255) NOT NULL,
    PARTNER_TYPE VARCHAR(100),
    
    -- Opportunity details
    OPPORTUNITY_TYPE VARCHAR(100),
    OPPORTUNITY_DESCRIPTION VARCHAR(4000),
    POTENTIAL_VALUE NUMBER(12,2),
    
    -- Partner information
    PARTNER_SIZE VARCHAR(100),
    PARTNER_INDUSTRY VARCHAR(255),
    PARTNER_LOCATION VARCHAR(255),
    
    -- Fit assessment
    STRATEGIC_FIT_SCORE FLOAT,
    CULTURAL_FIT_SCORE FLOAT,
    TECHNICAL_FIT_SCORE FLOAT,
    
    -- Next steps
    CONTACT_INFORMATION VARIANT,
    RECOMMENDED_APPROACH VARCHAR(2000),
    TIMELINE_ESTIMATE VARCHAR(500),
    
    -- Metadata layer
    LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFIDENCE_SCORE FLOAT DEFAULT 0.6,
    DATA_SOURCE VARCHAR(100) DEFAULT 'WEB_RESEARCH',
    
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS IX_INDUSTRY_TRENDS_SECTOR ON INDUSTRY_TRENDS(INDUSTRY_SECTOR);
CREATE INDEX IF NOT EXISTS IX_INDUSTRY_TRENDS_RELEVANCE ON INDUSTRY_TRENDS(RELEVANCE_SCORE);
CREATE INDEX IF NOT EXISTS IX_COMPETITOR_INTELLIGENCE_COMPETITOR ON COMPETITOR_INTELLIGENCE(COMPETITOR_NAME);
CREATE INDEX IF NOT EXISTS IX_PARTNERSHIP_OPPORTUNITIES_TYPE ON PARTNERSHIP_OPPORTUNITIES(OPPORTUNITY_TYPE);
