-- =====================================================================
-- Enhanced Security Roles and Access Control
-- =====================================================================

-- Create hierarchical roles
CREATE ROLE IF NOT EXISTS Unified_ROLE;
CREATE ROLE IF NOT EXISTS EXECUTIVE_ROLE;
CREATE ROLE IF NOT EXISTS BOARD_ROLE;
CREATE ROLE IF NOT EXISTS MANAGER_ROLE;
CREATE ROLE IF NOT EXISTS EMPLOYEE_ROLE;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS VIEWER_ROLE;

-- Grant role hierarchy
GRANT ROLE VIEWER_ROLE TO ROLE ANALYST_ROLE;
GRANT ROLE ANALYST_ROLE TO ROLE EMPLOYEE_ROLE;
GRANT ROLE EMPLOYEE_ROLE TO ROLE MANAGER_ROLE;
GRANT ROLE MANAGER_ROLE TO ROLE EXECUTIVE_ROLE;
GRANT ROLE EXECUTIVE_ROLE TO ROLE Unified_ROLE;

-- Unified-only access to Unified_INTELLIGENCE schema
GRANT USAGE ON SCHEMA Unified_INTELLIGENCE TO ROLE Unified_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA Unified_INTELLIGENCE TO ROLE Unified_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA Unified_INTELLIGENCE TO ROLE Unified_ROLE;
GRANT UPDATE ON ALL TABLES IN SCHEMA Unified_INTELLIGENCE TO ROLE Unified_ROLE;

-- Board role access to board materials only
GRANT USAGE ON SCHEMA Unified_INTELLIGENCE TO ROLE BOARD_ROLE;
GRANT SELECT ON Unified_INTELLIGENCE.BOARD_MATERIALS TO ROLE BOARD_ROLE;

-- Executive access to business data
GRANT USAGE ON SCHEMA HUBSPOT_DATA TO ROLE EXECUTIVE_ROLE;
GRANT USAGE ON SCHEMA GONG_DATA TO ROLE EXECUTIVE_ROLE;
GRANT USAGE ON SCHEMA SLACK_DATA TO ROLE EXECUTIVE_ROLE;
GRANT USAGE ON SCHEMA PAYREADY_CORE_SQL TO ROLE EXECUTIVE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HUBSPOT_DATA TO ROLE EXECUTIVE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA GONG_DATA TO ROLE EXECUTIVE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SLACK_DATA TO ROLE EXECUTIVE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PAYREADY_CORE_SQL TO ROLE EXECUTIVE_ROLE;
