-- =====================================================================
-- NETSUITE_DATA Schema - Financial and ERP Information
-- =====================================================================

USE DATABASE SOPHIA_AI;
CREATE SCHEMA IF NOT EXISTS NETSUITE_DATA;
USE SCHEMA NETSUITE_DATA;

-- General ledger entries
CREATE TABLE IF NOT EXISTS GENERAL_LEDGER (
    ENTRY_ID VARCHAR(255) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(255) NOT NULL,
    ACCOUNT_NAME VARCHAR(500),
    ACCOUNT_TYPE VARCHAR(100),
    
    -- Transaction details
    DEBIT_AMOUNT NUMBER(15,2) DEFAULT 0.00,
    CREDIT_AMOUNT NUMBER(15,2) DEFAULT 0.00,
    NET_AMOUNT NUMBER(15,2),
    TRANSACTION_DATE DATE NOT NULL,
    POSTING_DATE DATE,
    
    -- Transaction context
    TRANSACTION_TYPE VARCHAR(100),
    REFERENCE_NUMBER VARCHAR(255),
    DESCRIPTION VARCHAR(1000),
    MEMO VARCHAR(2000),
    
    -- Business context
    DEPARTMENT VARCHAR(255),
    CLASS VARCHAR(255),
    LOCATION VARCHAR(255),
    CUSTOMER_ID VARCHAR(255),
    VENDOR_ID VARCHAR(255),
    
    -- Reconciliation
    IS_RECONCILED BOOLEAN DEFAULT FALSE,
    RECONCILIATION_DATE DATE,
    RECONCILED_BY VARCHAR(255),
    
    -- AI Memory integration
    AI_MEMORY_EMBEDDING VECTOR(FLOAT, 768),
    AI_MEMORY_METADATA VARCHAR(16777216),
    AI_MEMORY_UPDATED_AT TIMESTAMP_NTZ,
    
    -- Metadata layer
    LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFIDENCE_SCORE FLOAT DEFAULT 1.0,
    DATA_SOURCE VARCHAR(100) DEFAULT 'NETSUITE',
    
    -- Audit trail
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    NETSUITE_CREATED_DATE TIMESTAMP_LTZ,
    NETSUITE_MODIFIED_DATE TIMESTAMP_LTZ
);

-- Purchase orders
CREATE TABLE IF NOT EXISTS PURCHASE_ORDERS (
    PO_ID VARCHAR(255) PRIMARY KEY,
    PO_NUMBER VARCHAR(100) NOT NULL,
    VENDOR_ID VARCHAR(255) NOT NULL,
    VENDOR_NAME VARCHAR(500),
    
    -- Order details
    ORDER_DATE DATE NOT NULL,
    EXPECTED_DELIVERY_DATE DATE,
    ACTUAL_DELIVERY_DATE DATE,
    STATUS VARCHAR(50),
    
    -- Financial details
    SUBTOTAL_AMOUNT NUMBER(15,2),
    TAX_AMOUNT NUMBER(15,2),
    SHIPPING_AMOUNT NUMBER(15,2),
    TOTAL_AMOUNT NUMBER(15,2),
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    
    -- Approval workflow
    REQUESTED_BY VARCHAR(255),
    APPROVED_BY VARCHAR(255),
    APPROVAL_DATE TIMESTAMP_LTZ,
    APPROVAL_STATUS VARCHAR(50),
    
    -- Business context
    DEPARTMENT VARCHAR(255),
    PROJECT_ID VARCHAR(255),
    COST_CENTER VARCHAR(255),
    
    -- AI Memory integration
    AI_MEMORY_EMBEDDING VECTOR(FLOAT, 768),
    AI_MEMORY_METADATA VARCHAR(16777216),
    AI_MEMORY_UPDATED_AT TIMESTAMP_NTZ,
    
    -- Metadata layer
    LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFIDENCE_SCORE FLOAT DEFAULT 1.0,
    DATA_SOURCE VARCHAR(100) DEFAULT 'NETSUITE',
    
    -- Audit trail
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Expense tracking
CREATE TABLE IF NOT EXISTS EXPENSE_REPORTS (
    EXPENSE_ID VARCHAR(255) PRIMARY KEY,
    EXPENSE_REPORT_ID VARCHAR(255),
    EMPLOYEE_ID VARCHAR(255) NOT NULL,
    
    -- Expense details
    EXPENSE_DATE DATE NOT NULL,
    EXPENSE_CATEGORY VARCHAR(255),
    EXPENSE_DESCRIPTION VARCHAR(1000),
    AMOUNT NUMBER(10,2) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    
    -- Business context
    DEPARTMENT VARCHAR(255),
    PROJECT_ID VARCHAR(255),
    CLIENT_ID VARCHAR(255),
    IS_BILLABLE BOOLEAN DEFAULT FALSE,
    
    -- Approval and reimbursement
    SUBMITTED_DATE DATE,
    APPROVED_DATE DATE,
    APPROVED_BY VARCHAR(255),
    REIMBURSED_DATE DATE,
    REIMBURSEMENT_AMOUNT NUMBER(10,2),
    
    -- Supporting documentation
    RECEIPT_ATTACHED BOOLEAN DEFAULT FALSE,
    RECEIPT_URL VARCHAR(2000),
    
    -- Metadata layer
    LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFIDENCE_SCORE FLOAT DEFAULT 1.0,
    DATA_SOURCE VARCHAR(100) DEFAULT 'NETSUITE',
    
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
-- Snowflake does not support traditional indexes; consider search optimization or clustering.

-- Create indexes
-- Snowflake does not support traditional indexes; consider search optimization or clustering.
-- CREATE INDEX IF NOT EXISTS IX_GENERAL_LEDGER_ACCOUNT_DATE ON GENERAL_LEDGER(ACCOUNT_ID, TRANSACTION_DATE);
-- -- Snowflake does not support traditional indexes; consider search optimization or clustering.
-- CREATE INDEX IF NOT EXISTS IX_PURCHASE_ORDERS_VENDOR_DATE ON PURCHASE_ORDERS(VENDOR_ID, ORDER_DATE);
-- -- Snowflake does not support traditional indexes; consider search optimization or clustering.
-- CREATE INDEX IF NOT EXISTS IX_EXPENSE_REPORTS_EMPLOYEE_DATE ON EXPENSE_REPORTS(EMPLOYEE_ID, EXPENSE_DATE);
