-- =====================================================================
-- PAYREADY_CORE_SQL Schema - Proprietary Business Logic
-- =====================================================================

USE DATABASE SOPHIA_AI;
CREATE SCHEMA IF NOT EXISTS PAYREADY_CORE_SQL;
USE SCHEMA PAYREADY_CORE_SQL;

-- Core payment transactions
CREATE TABLE IF NOT EXISTS PAYMENT_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(255) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    AMOUNT NUMBER(15,2) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    TRANSACTION_TYPE VARCHAR(100) NOT NULL,
    PAYMENT_METHOD VARCHAR(100),
    STATUS VARCHAR(50) NOT NULL,
    PROCESSING_DATE TIMESTAMP_LTZ,
    COMPLETED_DATE TIMESTAMP_LTZ,
    FAILURE_REASON VARCHAR(1000),
    
    -- Business context
    PROPERTY_ID VARCHAR(255),
    UNIT_ID VARCHAR(255),
    LEASE_ID VARCHAR(255),
    INVOICE_ID VARCHAR(255),
    
    -- Processing details
    PROCESSOR_NAME VARCHAR(100),
    PROCESSOR_TRANSACTION_ID VARCHAR(255),
    PROCESSOR_FEE NUMBER(15,2),
    PROCESSING_TIME_MS NUMBER,
    
    -- Risk and compliance
    RISK_SCORE FLOAT,
    FRAUD_FLAGS VARIANT,
    COMPLIANCE_STATUS VARCHAR(50),
    AML_STATUS VARCHAR(50),
    
    -- AI Memory integration
    AI_MEMORY_EMBEDDING VECTOR(FLOAT, 768),
    AI_MEMORY_METADATA VARCHAR(16777216),
    AI_MEMORY_UPDATED_AT TIMESTAMP_NTZ,
    
    -- Metadata layer
    LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFIDENCE_SCORE FLOAT DEFAULT 1.0,
    DATA_SOURCE VARCHAR(100) DEFAULT 'PAYREADY_CORE',
    
    -- Audit trail
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255)
);

-- Customer-facing features and configurations
CREATE TABLE IF NOT EXISTS CUSTOMER_FEATURES (
    FEATURE_ID VARCHAR(255) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    FEATURE_NAME VARCHAR(255) NOT NULL,
    FEATURE_CATEGORY VARCHAR(100),
    IS_ENABLED BOOLEAN DEFAULT FALSE,
    CONFIGURATION VARIANT,
    DEFAULT_CONFIGURATION VARIANT,
    CUSTOM_SETTINGS VARIANT,
    
    -- Feature metadata
    FEATURE_TIER VARCHAR(50),
    REQUIRES_SUBSCRIPTION BOOLEAN DEFAULT FALSE,
    MONTHLY_FEE NUMBER(10,2) DEFAULT 0.00,
    
    -- Usage tracking
    ACTIVATION_DATE TIMESTAMP_LTZ,
    LAST_USED_DATE TIMESTAMP_LTZ,
    USAGE_COUNT NUMBER DEFAULT 0,
    USAGE_FREQUENCY VARCHAR(50),
    
    -- Business impact
    CUSTOMER_SATISFACTION_IMPACT FLOAT,
    RETENTION_IMPACT FLOAT,
    REVENUE_IMPACT NUMBER(10,2),
    
    -- AI Memory integration
    AI_MEMORY_EMBEDDING VECTOR(FLOAT, 768),
    AI_MEMORY_METADATA VARCHAR(16777216),
    AI_MEMORY_UPDATED_AT TIMESTAMP_NTZ,
    
    -- Metadata layer
    LAST_UPDATED TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFIDENCE_SCORE FLOAT DEFAULT 1.0,
    DATA_SOURCE VARCHAR(100) DEFAULT 'PAYREADY_CORE',
    
    -- Audit trail
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    ENABLED_BY VARCHAR(255),
    DISABLED_BY VARCHAR(255),
    
    UNIQUE (CUSTOMER_ID, FEATURE_NAME)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS IX_PAYMENT_TRANSACTIONS_CUSTOMER_DATE ON PAYMENT_TRANSACTIONS(CUSTOMER_ID, PROCESSING_DATE);
CREATE INDEX IF NOT EXISTS IX_PAYMENT_TRANSACTIONS_STATUS ON PAYMENT_TRANSACTIONS(STATUS);
CREATE INDEX IF NOT EXISTS IX_CUSTOMER_FEATURES_CUSTOMER ON CUSTOMER_FEATURES(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IX_CUSTOMER_FEATURES_NAME ON CUSTOMER_FEATURES(FEATURE_NAME);
