#!/bin/bash

echo "==================================="
echo "DNS Update Required!"
echo "==================================="
echo ""
echo "Your DNS records are currently pointing to the wrong IP address."
echo ""
echo "CURRENT (INCORRECT):"
echo "  sophia-intel.ai → 198.99.82.151"
echo "  api.sophia-intel.ai → 198.99.82.151"
echo "  webhooks.sophia-intel.ai → 198.99.82.151"
echo ""
echo "SHOULD BE:"
echo "  sophia-intel.ai → 192.222.58.232"
echo "  api.sophia-intel.ai → 192.222.58.232"
echo "  webhooks.sophia-intel.ai → 192.222.58.232"
echo ""
echo "==================================="
echo "ACTION REQUIRED:"
echo "==================================="
echo ""
echo "1. Go to Namecheap: https://www.namecheap.com"
echo "2. Navigate to: Domain List → sophia-intel.ai → Manage → Advanced DNS"
echo "3. Update these A records:"
echo ""
echo "   Host: @        Value: 192.222.58.232    TTL: 30 min"
echo "   Host: api      Value: 192.222.58.232    TTL: 30 min"
echo "   Host: webhooks Value: 192.222.58.232    TTL: 5 min"
echo ""
echo "4. Save changes"
echo ""
echo "DNS propagation usually takes 5-30 minutes."
echo ""
echo "==================================="
echo "After updating, verify with:"
echo "==================================="
echo ""
echo "dig +short sophia-intel.ai"
echo "dig +short api.sophia-intel.ai"
echo "dig +short webhooks.sophia-intel.ai"
echo ""
echo "All should return: 192.222.58.232"
echo "" 