# Estuary Flow Collection - Gong V2 Sales Intelligence
# This collection ingests real-time call data from Gong via MCP server webhook

collections:
  sophia-ai/gong-calls:
    schema:
      type: object
      required: [call_id, timestamp]
      properties:
        call_id: 
          type: string
          description: Unique Gong call identifier
        title:
          type: string
          description: Call title/subject
        timestamp:
          type: string
          format: date-time
          description: Call completion timestamp
        duration:
          type: integer
          description: Call duration in seconds
        participants:
          type: array
          items:
            type: object
            properties:
              name: { type: string }
              email: { type: string }
              role: { type: string, enum: [host, attendee] }
        transcript:
          type: string
          description: Full call transcript
        sentiment:
          type: number
          minimum: -1
          maximum: 1
          description: Overall call sentiment score
        topics:
          type: array
          items: { type: string }
          description: Detected discussion topics
        action_items:
          type: array
          items:
            type: object
            properties:
              text: { type: string }
              assignee: { type: string }
              due_date: { type: string, format: date }
        metrics:
          type: object
          properties:
            talk_ratio: { type: number }
            question_count: { type: integer }
            monologue_duration: { type: integer }
        
    key: [/call_id]
    
    capture:
      endpoint:
        connector:
          image: ghcr.io/estuary/source-http-ingest:latest
          config:
            endpoint:
              $ref: secrets.yaml#/gong_webhook_endpoint
            auth:
              type: bearer
              token:
                $ref: secrets.yaml#/estuary_gong_token
            
    # Automatic backfill from Gong API
    backfill:
      enabled: true
      start_date: "2024-01-01T00:00:00Z"
      
    # Quality validations
    expect:
      - description: "Call ID must be present"
        when: { type: object }
        must:
          properties:
            call_id: { type: string, minLength: 1 }
            
      - description: "Duration must be positive"
        when: { properties: { duration: { type: integer } } }
        must:
          properties:
            duration: { minimum: 0 }
            
      - description: "Sentiment must be normalized"
        when: { properties: { sentiment: { type: number } } }
        must:
          properties:
            sentiment: { minimum: -1, maximum: 1 }

# Metadata
metadata:
  owner: data-team
  owner_slack: "#data-pipelines"
  description: "Real-time Gong call intelligence ingestion"
  sla: 
    latency_seconds: 5
    availability_percent: 99.9
  tags:
    - sales-intelligence
    - real-time
    - mcp-v2 