captures:
  Pay_Ready/usergems-capture:
    bindings:
    - resource:
        endpoint: contacts
      target: Pay_Ready/usergems-contacts
    - resource:
        endpoint: tracking
      target: Pay_Ready/usergems-tracking
    endpoint:
      connector:
        config:
          authentication:
            token: ${USERGEMS_API_KEY}
            type: bearer
          base_url: https://api.usergems.com/v1
          endpoints:
          - name: contacts
            path: /contacts
          - name: tracking
            path: /tracking
        image: ghcr.io/estuary/source-http-inbound:dev
