apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-frontend-test
  namespace: sophia-ai-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sophia-frontend-test
  template:
    metadata:
      labels:
        app: sophia-frontend-test
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            nvidia.com/gpu: "0"
          limits:
            memory: "256Mi"
            cpu: "200m"
            nvidia.com/gpu: "0"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: frontend-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: frontend-content
        configMap:
          name: frontend-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sophia-ai-prod
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        server {
            listen 80;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;
            
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            location / {
                try_files $uri $uri/ /index.html;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-content
  namespace: sophia-ai-prod
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sophia AI - Frontend Loading</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                margin: 0;
                padding: 0;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                text-align: center;
            }
            .container {
                max-width: 600px;
                padding: 2rem;
                background: rgba(255, 255, 255, 0.1);
                border-radius: 20px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
            }
            h1 {
                font-size: 3rem;
                margin-bottom: 1rem;
                text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
            }
            .status {
                font-size: 1.2rem;
                margin: 1rem 0;
                padding: 1rem;
                background: rgba(255, 255, 255, 0.1);
                border-radius: 10px;
            }
            .success {
                background: rgba(34, 197, 94, 0.2);
                border: 1px solid rgba(34, 197, 94, 0.3);
            }
            .loading {
                animation: pulse 2s infinite;
            }
            @keyframes pulse {
                0% { opacity: 0.6; }
                50% { opacity: 1; }
                100% { opacity: 0.6; }
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Sophia AI</h1>
            <div class="status success">
                ✅ Frontend Successfully Deployed!
            </div>
            <div class="status">
                🌐 sophia-intel.ai is now serving the React frontend
            </div>
            <div class="status loading">
                🔄 Full React app loading...
            </div>
            <p>This temporary page confirms the frontend deployment is working.</p>
            <p>The full React dashboard will be available shortly.</p>
        </div>
        
        <script>
            // Auto-refresh every 30 seconds to check for React app
            setTimeout(() => {
                window.location.reload();
            }, 30000);
        </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-frontend-test-service
  namespace: sophia-ai-prod
spec:
  selector:
    app: sophia-frontend-test
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 