---
apiVersion: v1
kind: Namespace
metadata:
  name: sophia-ai-prod
  labels:
    name: sophia-ai-prod
    environment: production

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sophia-ai-config
  namespace: sophia-ai-prod
data:
  ENVIRONMENT: "prod"
  PULUMI_ORG: "scoobyjava-org"
  PULUMI_STACK: "scoobyjava-org/default/sophia-ai-production"
  LOG_LEVEL: "INFO"
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "8080"

---
apiVersion: v1
kind: Secret
metadata:
  name: sophia-ai-secrets
  namespace: sophia-ai-prod
type: Opaque
data:
  # These will be populated by Pulumi ESC
  pulumi-access-token: ""  # Base64 encoded

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-ai-backend
  namespace: sophia-ai-prod
  labels:
    app: sophia-ai-backend
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sophia-ai-backend
  template:
    metadata:
      labels:
        app: sophia-ai-backend
        version: v1
    spec:
      containers:
      - name: sophia-ai-backend
        image: scoobyjava15/sophia-ai-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        # Standard Environment Configuration
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: ENVIRONMENT
        - name: PULUMI_ORG
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: PULUMI_ORG
        - name: PULUMI_STACK
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: PULUMI_STACK
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: LOG_LEVEL
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: DOMAIN
        # Secret References (Pulumi ESC Integration)
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: ANTHROPIC_API_KEY
        - name: QDRANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: QDRANT_API_KEY
        - name: GONG_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: GONG_API_KEY
        - name: HUBSPOT_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: HUBSPOT_API_KEY
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: SLACK_WEBHOOK_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-ai-mcp-orchestrator
  namespace: sophia-ai-prod
  labels:
    app: sophia-ai-mcp-orchestrator
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sophia-ai-mcp-orchestrator
  template:
    metadata:
      labels:
        app: sophia-ai-mcp-orchestrator
        version: v1
    spec:
      containers:
      - name: mcp-orchestrator
        image: scoobyjava15/sophia-ai-mcp-orchestrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        # Standard Environment Configuration
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: ENVIRONMENT
        - name: PULUMI_ORG
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: PULUMI_ORG
        - name: PULUMI_STACK
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: PULUMI_STACK
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: LOG_LEVEL
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: sophia-ai-config
              key: DOMAIN
        # Service Configuration
        - name: BACKEND_URL
          value: "http://sophia-ai-backend:8000"
        # Secret References (Pulumi ESC Integration)
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: ANTHROPIC_API_KEY
        - name: LINEAR_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: LINEAR_API_KEY
        - name: ASANA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: ASANA_API_TOKEN
        - name: NOTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-ai-secrets
              key: NOTION_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: sophia-ai-backend
  namespace: sophia-ai-prod
  labels:
    app: sophia-ai-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: sophia-ai-backend

---
apiVersion: v1
kind: Service
metadata:
  name: sophia-ai-mcp-orchestrator
  namespace: sophia-ai-prod
  labels:
    app: sophia-ai-mcp-orchestrator
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: sophia-ai-mcp-orchestrator

---
apiVersion: v1
kind: Service
metadata:
  name: sophia-ai-loadbalancer
  namespace: sophia-ai-prod
  labels:
    app: sophia-ai-backend
spec:
  type: LoadBalancer
  loadBalancerIP: 192.222.58.232
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: sophia-ai-backend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sophia-ai-ingress
  namespace: sophia-ai-prod
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "sophia-ai-prod-auth@kubernetescrd"
spec:
  rules:
  - host: sophia-ai.lambda-labs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sophia-ai-backend
            port:
              number: 8000
  - host: orchestrator.sophia-ai.lambda-labs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sophia-ai-mcp-orchestrator
            port:
              number: 8001

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sophia-ai-backend-hpa
  namespace: sophia-ai-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sophia-ai-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sophia-ai-mcp-orchestrator-hpa
  namespace: sophia-ai-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sophia-ai-mcp-orchestrator
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sophia-ai-network-policy
  namespace: sophia-ai-prod
spec:
  podSelector:
    matchLabels:
      app: sophia-ai-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: sophia-ai-prod
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 9090
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sophia-ai-backend-pdb
  namespace: sophia-ai-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: sophia-ai-backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sophia-ai-mcp-orchestrator-pdb
  namespace: sophia-ai-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sophia-ai-mcp-orchestrator 