values:
  sophia:
    infrastructure:
      lambda_labs:
        # Core Configuration
        api_key: ${secrets.LAMBDA_LABS_API_KEY}
        region: ${secrets.LAMBDA_LABS_REGION}

        # SSH Configuration
        ssh:
          key_name: ${secrets.LAMBDA_LABS_SSH_KEY_NAME}
          private_key: ${secrets.LAMBDA_LABS_SSH_PRIVATE_KEY}

        # Instance Configuration
        instances:
          type: ${secrets.LAMBDA_LABS_INSTANCE_TYPE}
          cluster_size: ${secrets.LAMBDA_LABS_CLUSTER_SIZE}
          max_cluster_size: ${secrets.LAMBDA_LABS_MAX_CLUSTER_SIZE}

          # Instance Names
          master:
            name: lynn-sophia-h200-master-01
          workers:
            - name: lynn-sophia-h200-worker-01
            - name: lynn-sophia-h200-worker-02

        # Storage Configuration
        storage:
          shared_fs_id: ${secrets.LAMBDA_LABS_SHARED_FS_ID}
          shared_fs_mount: ${secrets.LAMBDA_LABS_SHARED_FS_MOUNT}
          size_tb: 10
          type: high-performance-nfs

        # Auto-Scaling
        autoscaling:
          group_name: ${secrets.LAMBDA_LABS_ASG_NAME}
          min_nodes: 3
          max_nodes: 16
          scale_down_delay_minutes: 10
          scale_up_threshold_cpu: 80
          scale_down_threshold_cpu: 20

        # H200 Specific Configuration
        gpu:
          type: H200
          memory_gb: 141
          memory_type: HBM3e
          memory_pools:
            active_models: 60
            inference_cache: 40
            vector_cache: 30
            buffer: 11

        # Network Configuration
        network:
          security_group: lynn-sophia-h200-sg
          ports:
            ssh: 22
            kubernetes_api: 6443
            node_port_range: 30000-32767

        # Monitoring
        monitoring:
          prometheus_port: 9090
          grafana_port: 3000
          node_exporter_port: 9100
          nvidia_dcgm_port: 9400

secrets:
  # These will be synced from GitHub Organization Secrets
  LAMBDA_LABS_API_KEY:
    fn::secret: ${LAMBDA_LABS_API_KEY}
  LAMBDA_LABS_SSH_KEY_NAME:
    fn::secret: ${LAMBDA_LABS_SSH_KEY_NAME}
  LAMBDA_LABS_SSH_PRIVATE_KEY:
    fn::secret: ${LAMBDA_LABS_SSH_PRIVATE_KEY}
  LAMBDA_LABS_REGION:
    fn::secret: ${LAMBDA_LABS_REGION}
  LAMBDA_LABS_INSTANCE_TYPE:
    fn::secret: ${LAMBDA_LABS_INSTANCE_TYPE}
  LAMBDA_LABS_CLUSTER_SIZE:
    fn::secret: ${LAMBDA_LABS_CLUSTER_SIZE}
  LAMBDA_LABS_MAX_CLUSTER_SIZE:
    fn::secret: ${LAMBDA_LABS_MAX_CLUSTER_SIZE}
  LAMBDA_LABS_SHARED_FS_ID:
    fn::secret: ${LAMBDA_LABS_SHARED_FS_ID}
  LAMBDA_LABS_SHARED_FS_MOUNT:
    fn::secret: ${LAMBDA_LABS_SHARED_FS_MOUNT}
  LAMBDA_LABS_ASG_NAME:
    fn::secret: ${LAMBDA_LABS_ASG_NAME}

# Environment-specific configuration
environments:
  production:
    imports:
      - scoobyjava-org/default/sophia-ai-production
  h200-production:
    imports:
      - scoobyjava-org/default/sophia-ai-h200-production
