# Enhanced Secret Sync Monitor Configuration for Sophia AI
# Configuration for infrastructure/esc/enhanced_secret_sync_monitor.py

# GitHub Organization Configuration
github:
  org: "ai-cherry"
  token: "${GITHUB_TOKEN}"  # Will be loaded from environment
  api_timeout: 30
  rate_limit_buffer: 10  # Requests to keep below rate limit

# Pulumi ESC Configuration
pulumi:
  org: "scoobyjava-org"
  environment: "default/sophia-ai-production"
  timeout: 60
  max_retries: 3

# Monitoring Settings
monitoring:
  check_interval: 300  # 5 minutes between health checks
  health_retention_days: 30  # Keep 30 days of health history
  enable_alerts: true
  enable_auto_healing: false  # Enable with caution
  enable_drift_detection: true
  drift_check_interval: 3600  # 1 hour between drift checks

  # Performance monitoring
  track_performance_metrics: true
  max_history_entries: 1000
  metrics_retention_days: 7

# Alert Configuration
alerts:
  # Slack integration
  slack:
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#sophia-ai-alerts"
    username: "Sophia Secret Monitor"
    icon_emoji: ":lock:"

  # Email notifications
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
    recipients:
      - "alerts@sophia-ai.com"

  # Alert thresholds
  thresholds:
    sync_health_percentage: 85.0  # Alert if sync health below 85%
    max_sync_duration: 300.0  # Alert if sync takes >5 minutes
    max_drift_percentage: 10.0  # Alert if >10% drift detected
    max_consecutive_failures: 3  # Alert after 3 consecutive failures
    api_latency_threshold: 5.0  # Alert if API latency >5 seconds

  # Alert frequency limits
  rate_limiting:
    max_alerts_per_hour: 10
    cooldown_period: 3600  # 1 hour cooldown for similar alerts

# Auto-healing Configuration
auto_healing:
  enabled: false  # Enable with extreme caution
  max_healing_attempts: 3
  healing_cooldown: 1800  # 30 minutes between healing attempts

  # Actions that auto-healing can perform
  allowed_actions:
    - "github_to_esc_sync"
    - "validate_sync_status"
    - "clear_cache"

  # Actions that require manual approval
  restricted_actions:
    - "esc_to_github_sync"  # Never auto-sync ESC to GitHub
    - "delete_secrets"
    - "modify_mappings"

# Performance Optimization
performance:
  # Connection pooling
  max_concurrent_connections: 10
  connection_timeout: 30

  # Caching
  enable_response_caching: true
  cache_ttl: 300  # 5 minutes
  max_cache_size: 100

  # Batch processing
  batch_size: 50
  batch_timeout: 60

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # File logging
  file_logging:
    enabled: true
    log_file: "logs/secret_sync_monitor.log"
    max_file_size: "100MB"
    backup_count: 5

  # Structured logging for analysis
  structured_logging:
    enabled: true
    output_file: "logs/secret_sync_metrics.jsonl"
    include_performance_data: true

# Dashboard Integration
dashboard:
  enabled: true
  update_interval: 60  # 1 minute updates for dashboard

  # Metrics to expose
  exposed_metrics:
    - "sync_health_percentage"
    - "api_latency"
    - "sync_duration"
    - "error_rate"
    - "success_rate"
    - "drift_percentage"

  # Dashboard endpoints
  endpoints:
    health: "/api/v1/secret-sync/health"
    metrics: "/api/v1/secret-sync/metrics"
    alerts: "/api/v1/secret-sync/alerts"

# Security Settings
security:
  # Secret scanning
  scan_for_exposed_secrets: true
  scan_patterns:
    - "ghp_[A-Za-z0-9_]{36}"  # GitHub PAT
    - "pul-[A-Za-z0-9]{40}"   # Pulumi token

  # Encryption settings
  encrypt_logs: false
  encrypt_cache: false

  # Audit settings
  audit_trail:
    enabled: true
    audit_file: "logs/secret_sync_audit.log"
    include_full_payloads: false  # Security: don't log secret values

# Development and Testing
development:
  dry_run_by_default: false
  enable_debug_endpoints: false
  mock_external_calls: false

  # Test configuration
  test_mode:
    enabled: false
    mock_github_responses: false
    mock_pulumi_responses: false
    use_test_secrets: false

# Backup and Recovery
backup:
  enabled: true
  backup_interval: 86400  # 24 hours
  backup_retention_days: 30
  backup_location: "backups/secret-sync"

  # What to backup
  backup_items:
    - "health_history"
    - "performance_metrics"
    - "alert_history"
    - "configuration_snapshots"

# Integration with Existing Sophia AI Systems
sophia_integration:
  # Enhanced monitoring integration
  enhanced_monitoring:
    enabled: true
    endpoint: "http://localhost:8080/monitoring/secret-sync"

  # Grafana dashboard
  grafana:
    enabled: true
    dashboard_id: "sophia-secret-sync"

  # Prometheus metrics
  prometheus:
    enabled: true
    metrics_port: 9091
    metrics_path: "/metrics"

  # AI Memory integration
  ai_memory:
    enabled: true
    store_health_insights: true
    category: "infrastructure_monitoring"
