# Sophia Intelligence Platform - Pulumi ESC Configuration
# DNS and Infrastructure Management with IP Whitelisting

imports:
  - sophia-ai-platform-base # Inherit from existing base configuration

values:
  # Platform Identity
  platform:
    name: "sophia-intelligence-platform"
    domain: "sophia-intel.ai"
    version: "v1.0.0"
    environment: "${pulumi.stack}"

  # IP Address Management (from GitHub Organization Secrets)
  ip_addresses:
    lambda_labs:
      fn::secret: "${LAMBDA_IP_ADDRESS}" # 170.9.9.253 - Production server
    github_actions:
      fn::secret: "${GH_IP_ADDRESS}" # 140.82.112.2 - CI/CD context
    pulumi_cloud:
      fn::secret: "${PULUMI_IP_ADDRESS}" # 34.74.88.2 - Deployment context

    # Derived configurations
    primary_server: "${ip_addresses.lambda_labs}" # Main server for DNS records
    whitelisted_ips:
      - "${ip_addresses.lambda_labs}"
      - "${ip_addresses.github_actions}"
      - "${ip_addresses.pulumi_cloud}"

  # DNS Configuration
  dns:
    provider: "namecheap"
    domain: "${platform.domain}"
    ttl: 300
    records:
      # Root domain
      root:
        type: "A"
        value: "${ip_addresses.lambda_labs}"
        name: "@"

      # Core subdomains
      api:
        type: "A"
        value: "${ip_addresses.lambda_labs}"
        name: "api"

      webhooks:
        type: "A"
        value: "${ip_addresses.lambda_labs}"
        name: "webhooks"

      dashboard:
        type: "A"
        value: "${ip_addresses.lambda_labs}"
        name: "dashboard"

      sophia:
        type: "A"
        value: "${ip_addresses.lambda_labs}"
        name: "sophia"

      dev:
        type: "A"
        value: "${ip_addresses.lambda_labs}"
        name: "dev"

      # Wildcard for future subdomains
      wildcard:
        type: "A"
        value: "${ip_addresses.lambda_labs}"
        name: "*"

  # Namecheap API Configuration
  namecheap:
    api_user:
      fn::secret: "${NAMECHEAP_API_USER}"
    api_key:
      fn::secret: "${NAMECHEAP_API_KEY}"
    username:
      fn::secret: "${NAMECHEAP_USERNAME}"
    sandbox: false
    endpoint: "https://api.namecheap.com/xml.response"

    # IP Context Detection for API calls
    client_ip_detection:
      local_dev: "${ip_addresses.lambda_labs}"
      github_actions: "${ip_addresses.github_actions}"
      pulumi_cloud: "${ip_addresses.pulumi_cloud}"
      fallback: "${ip_addresses.lambda_labs}"

  # SSL/TLS Configuration
  ssl:
    provider: "letsencrypt"
    email:
      fn::secret: "${SSL_ADMIN_EMAIL}"
    domains:
      - "${platform.domain}"
      - "*.${platform.domain}"

  # Monitoring and Health Checks
  monitoring:
    dns_health_check: true
    ping_endpoints:
      - "https://${platform.domain}"
      - "https://api.${platform.domain}"
      - "https://dashboard.${platform.domain}"
    alert_email:
      fn::secret: "${ALERT_EMAIL}"

  # Deployment Context Detection
  deployment:
    context_detection:
      environment_variables:
        - "GITHUB_ACTIONS" # GitHub Actions context
        - "PULUMI_COMMAND" # Pulumi CLI context
        - "LAMBDA_LABS_CONTEXT" # Local dev context

      ip_mapping:
        github_actions: "${ip_addresses.github_actions}"
        pulumi_cloud: "${ip_addresses.pulumi_cloud}"
        local_dev: "${ip_addresses.lambda_labs}"
        default: "${ip_addresses.lambda_labs}"

  # Security Configuration
  security:
    api_rate_limiting: true
    dns_sec: true
    ip_whitelist_enforcement: true
    secret_rotation_days: 90
