imports:
  - esc:
      organization: scoobyjava-org
      project: default
      environment: shared-secrets

values:
  ai_intelligence:
    # LangGraph is now the sole orchestration framework - Agno deprecated
    # agno:
    #   api_key:
    #     fn::secret: "${AGNO_API_KEY}"  # REMOVED: Agno framework deprecated
    openrouter:
      api_key:
        fn::secret: "${OPENROUTER_API_KEY}"
    portkey:
      api_key:
        fn::secret: "${PORTKEY_API_KEY}"
      virtual_key_prod:
        fn::secret: "${PORTKEY_VIRTUAL_KEY_PROD}"
    openai:
      api_key:
        fn::secret: "${OPENAI_API_KEY}"
    anthropic:
      api_key:
        fn::secret: "${ANTHROPIC_API_KEY}"
    huggingface:
      api_token:
        fn::secret: "${HUGGINGFACE_API_TOKEN}"
    langchain:
      api_key:
        fn::secret: "${LANGCHAIN_API_KEY}"
    arize:
      api_key:
        fn::secret: "${ARIZE_API_KEY}"
      space_id:
        fn::secret: "${ARIZE_SPACE_ID}"
    mistral:
      api_key:
        fn::secret: "${MISTRAL_API_KEY}"
    deepseek:
      api_key:
        fn::secret: "${DEEPSEEK_API_KEY}"
    codestral:
      api_key:
        fn::secret: "${CODESTRAL_API_KEY}"
    togetherai:
      api_key:
        fn::secret: "${TOGETHERAI_API_KEY}"
    xai:
      api_key:
        fn::secret: "${XAI_API_KEY}"
    venice_ai:
      api_key:
        fn::secret: "${VENICE_AI_API_KEY}"
    llama:
      api_key:
        fn::secret: "${LLAMA_API_KEY}"

  data_intelligence:
    vector_databases:
      pinecone:
        api_key:
          fn::secret: "${PINECONE_API_KEY}"
        environment:
          fn::secret: "${PINECONE_ENVIRONMENT}"
        index_name:
          fn::secret: "${PINECONE_INDEX_NAME}"
      weaviate:
        api_key:
          fn::secret: "${WEAVIATE_API_KEY}"
        url:
          fn::secret: "${WEAVIATE_URL}"
    research_tools:
      apify:
        api_token:
          fn::secret: "${APIFY_API_TOKEN}"
      serp:
        api_key:
          fn::secret: "${SERP_API_KEY}"
      tavily:
        api_key:
          fn::secret: "${TAVILY_API_KEY}"
    data_infrastructure:
      snowflake:
        account:
          fn::secret: "${SNOWFLAKE_ACCOUNT}"
        user:
          fn::secret: "${SNOWFLAKE_USER}"
      database_url:
        fn::secret: "${DATABASE_URL}"

  infrastructure:
    observability:
      grafana:
        url:
          fn::secret: "${GRAFANA_URL}"
        username:
          fn::secret: "${GRAFANA_USERNAME}"
        password:
          fn::secret: "${GRAFANA_PASSWORD}"
      prometheus:
        url:
          fn::secret: "${PROMETHEUS_URL}"
    communication:
      slack:
        bot_token:
          fn::secret: "${SLACK_BOT_TOKEN}"
        app_token:
          fn::secret: "${SLACK_APP_TOKEN}"
        signing_secret:
          fn::secret: "${SLACK_SIGNING_SECRET}"
    security:
      jwt_secret:
        fn::secret: "${JWT_SECRET}"
      encryption_key:
        fn::secret: "${ENCRYPTION_KEY}"
    lambda_labs:
      api_key:
        fn::secret: "${LAMBDA_LABS_API_KEY}"
      control_plane_ip:
        fn::secret: "${LAMBDA_LABS_CONTROL_PLANE_IP}"
      ssh_key_name:
        fn::secret: "${LAMBDA_LABS_SSH_KEY_NAME}"
    docker:
      username:
        fn::secret: "${DOCKER_USER_NAME}"
      token:
        fn::secret: "${DOCKER_PERSONAL_ACCESS_TOKEN}"
    pulumi:
      access_token:
        fn::secret: "${PULUMI_ACCESS_TOKEN}"
      org:
        fn::secret: "${PULUMI_ORG}"

  business_intelligence:
    gong:
      access_key:
        fn::secret: "${GONG_ACCESS_KEY}"
      client_secret:
        fn::secret: "${GONG_CLIENT_SECRET}"
    hubspot:
      access_token:
        fn::secret: "${HUBSPOT_ACCESS_TOKEN}"
    linear:
      api_key:
        fn::secret: "${LINEAR_API_KEY}"
    notion:
      api_key:
        fn::secret: "${NOTION_API_KEY}"

rotation:
  strategy: two-secret
  auditing:
    enabled: true
    log_file: "/var/log/esc_rotation.log"

environmentVariables:
  OPENAI_API_KEY: ${ai_intelligence.openai.api_key}
  ANTHROPIC_API_KEY: ${ai_intelligence.anthropic.api_key}
  HUGGINGFACE_API_TOKEN: ${ai_intelligence.huggingface.api_token}
  LANGCHAIN_API_KEY: ${ai_intelligence.langchain.api_key}
  PORTKEY_API_KEY: ${ai_intelligence.portkey.api_key}
  PORTKEY_VIRTUAL_KEY_PROD: ${ai_intelligence.portkey.virtual_key_prod}
  OPENROUTER_API_KEY: ${ai_intelligence.openrouter.api_key}
  MISTRAL_API_KEY: ${ai_intelligence.mistral.api_key}
  DEEPSEEK_API_KEY: ${ai_intelligence.deepseek.api_key}
  CODESTRAL_API_KEY: ${ai_intelligence.codestral.api_key}
  TOGETHERAI_API_KEY: ${ai_intelligence.togetherai.api_key}
  XAI_API_KEY: ${ai_intelligence.xai.api_key}
  VENICE_AI_API_KEY: ${ai_intelligence.venice_ai.api_key}
  LLAMA_API_KEY: ${ai_intelligence.llama.api_key}

  ARIZE_API_KEY: ${infrastructure.observability.arize.api_key}
  ARIZE_SPACE_ID: ${infrastructure.observability.arize.space_id}
  GRAFANA_URL: ${infrastructure.observability.grafana.url}
  GRAFANA_USERNAME: ${infrastructure.observability.grafana.username}
  GRAFANA_PASSWORD: ${infrastructure.observability.grafana.password}
  PROMETHEUS_URL: ${infrastructure.observability.prometheus.url}

  PINECONE_API_KEY: ${data_intelligence.vector_databases.pinecone.api_key}
  PINECONE_ENVIRONMENT: ${data_intelligence.vector_databases.pinecone.environment}
  PINECONE_INDEX_NAME: ${data_intelligence.vector_databases.pinecone.index_name}
  WEAVIATE_API_KEY: ${data_intelligence.vector_databases.weaviate.api_key}
  WEAVIATE_URL: ${data_intelligence.vector_databases.weaviate.url}

  GONG_ACCESS_KEY: ${business_intelligence.gong.access_key}
  GONG_CLIENT_SECRET: ${business_intelligence.gong.client_secret}
  HUBSPOT_ACCESS_TOKEN: ${business_intelligence.hubspot.access_token}
  LINEAR_API_KEY: ${business_intelligence.linear.api_key}

  SLACK_BOT_TOKEN: ${infrastructure.communication.slack.bot_token}
  SLACK_APP_TOKEN: ${infrastructure.communication.slack.app_token}

  SNOWFLAKE_ACCOUNT: ${data_intelligence.data_infrastructure.snowflake.account}
  SNOWFLAKE_USER: ${data_intelligence.data_infrastructure.snowflake.user}
  DATABASE_URL: ${data_intelligence.data_infrastructure.database_url}

  APIFY_API_TOKEN: ${data_intelligence.research_tools.apify.api_token}
  SERP_API_KEY: ${data_intelligence.research_tools.serp.api_key}
  TAVILY_API_KEY: ${data_intelligence.research_tools.tavily.api_key}

  JWT_SECRET: ${infrastructure.security.jwt_secret}
  ENCRYPTION_KEY: ${infrastructure.security.encryption_key}
