name: sophia-ai-vercel-infrastructure
runtime: nodejs
description: Comprehensive Pulumi infrastructure for Sophia AI Vercel deployment and DNS automation

template:
  config:
    deleteLegacyOrchestraProjects:
      description: Whether to delete legacy orchestra projects (orchestra-main, dashboard, admin-interface)
      default: false
    vercel:token:
      description: Vercel API access token
      secret: true
    vercel:teamId:
      description: Vercel team/organization ID (optional)
    namecheap:apiKey:
      description: Namecheap API key for DNS automation
      secret: true
    namecheap:apiUser:
      description: Namecheap API username
    namecheap:clientIp:
      description: Client IP address for Namecheap API (optional)
      default: "127.0.0.1"
