apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage
  namespace: sophia-ai-prod
  labels:
    app.kubernetes.io/name: postgres-storage
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sophia-ai
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path  # K3s default storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage
  namespace: sophia-ai-prod
  labels:
    app.kubernetes.io/name: redis-storage
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: sophia-ai
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path  # K3s default storage class

---
# Additional PVC for Vector Database persistence
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage
  namespace: sophia-ai-prod
  labels:
    app.kubernetes.io/name: qdrant-storage
    app.kubernetes.io/component: vector-db
    app.kubernetes.io/part-of: sophia-ai
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path  # K3s default storage class

---
# MCP Server persistent storage for AI Memory
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-ai-memory-storage
  namespace: sophia-ai-prod
  labels:
    app.kubernetes.io/name: mcp-ai-memory-storage
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/part-of: sophia-ai
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path  # K3s default storage class 