apiVersion: v1
kind: Secret
metadata:
  name: sophia-ai-secrets
  namespace: sophia-ai-prod
  annotations:
    pulumi.com/esc-env: "scoobyjava-org/default/sophia-ai-production"
    app.kubernetes.io/name: sophia-ai-secrets
    app.kubernetes.io/component: secret-management
    app.kubernetes.io/part-of: sophia-ai
type: Opaque
stringData:
  # AI Service API Keys
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  
  # Vector Database Keys
  QDRANT_API_KEY: ""
  QDRANT_URL: ""
  
  # Business Intelligence APIs
  GONG_API_KEY: ""
  HUBSPOT_API_KEY: ""
  SLACK_WEBHOOK_URL: ""
  
  # Infrastructure Keys
  DOCKER_HUB_ACCESS_TOKEN: ""
  LAMBDA_LABS_API_KEY: ""
  
  # Development Tools
  LINEAR_API_KEY: ""
  ASANA_API_TOKEN: ""
  NOTION_API_KEY: ""
  
  # Security & Monitoring
  GITHUB_TOKEN: ""
  FIGMA_PAT: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sophia-ai-config
  namespace: sophia-ai-prod
data:
  ENVIRONMENT: "prod"
  PULUMI_ORG: "scoobyjava-org"
  PULUMI_STACK: "sophia-ai-production"
  LOG_LEVEL: "INFO"
  DOMAIN: "sophia-intel.ai"
  API_DOMAIN: "api.sophia-intel.ai"
  GRAFANA_DOMAIN: "grafana.sophia-intel.ai"
  
  # Service Ports
  BACKEND_PORT: "8000"
  FRONTEND_PORT: "3000"
  REDIS_PORT: "6379"
  POSTGRES_PORT: "5432"
  
  # Application Configuration
  MAX_WORKERS: "4"
  HEALTH_CHECK_INTERVAL: "30"
  RETRY_ATTEMPTS: "3"
  TIMEOUT_SECONDS: "30" 