# Source-Coverage Registry (SCR) Template
# Copy or rename this file to `config/mcp/<server-name>_coverage.yml`
# and fill in the details for the given MCP server.
#
# Fields:
#   vendor:          Human-readable vendor name (e.g. "HubSpot")
#   api_name:        Official API name (e.g. "HubSpot CRM REST API")
#   api_version:     The version this coverage file targets
#   retrieved_at:    ISO-8601 timestamp when spec was last confirmed
#   endpoints:       List of endpoints / GraphQL fields / webhook topics.
#                    Each entry MUST contain:
#                      path:   REST path or GraphQL field
#                      method: HTTP verb (GET, POST, etc.) or "GRAPHQL"
#                      status: implemented | ignored-by-design | na
#                      notes:  Optional free-text explanation
#
# Example:
# vendor: HubSpot
# api_name: HubSpot CRM REST API
# api_version: v3
# retrieved_at: "2025-07-09T12:00:00Z"
# endpoints:
#   - path: /crm/v3/objects/contacts
#     method: GET
#     status: implemented
#     notes: "Incremental sync via /search endpoint"
#
vendor: "<replace_me>"
api_name: "<replace_me>"
api_version: "<replace_me>"
retrieved_at: "<replace_me>"
endpoints: []