apiVersion: v1
kind: Namespace
metadata:
  name: sophia-memory
  labels:
    app.kubernetes.io/part-of: sophia-ai
    app.kubernetes.io/component: memory

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem0-persistent-server
  namespace: sophia-memory
  labels:
    app: mem0-server
    app.kubernetes.io/name: mem0
    app.kubernetes.io/component: memory
    app.kubernetes.io/part-of: sophia-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mem0-server
  template:
    metadata:
      labels:
        app: mem0-server
        app.kubernetes.io/name: mem0
        app.kubernetes.io/component: memory
    spec:
      containers:
        - name: mem0
          image: mem0ai/mem0:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sophia-secrets
                  key: pinecone-api-key
            - name: PINECONE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: sophia-secrets
                  key: pinecone-environment
            - name: POSTGRES_URL
              value: "postgresql://mem0:mem0pass@postgres-mem0:5432/mem0db"
            - name: REDIS_URL
              value: "redis://redis-mem0:6379"
            - name: MEM0_CONFIG_PATH
              value: "/config/mem0.yaml"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: mem0-config

---
apiVersion: v1
kind: Service
metadata:
  name: mem0-server
  namespace: sophia-memory
  labels:
    app: mem0-server
spec:
  selector:
    app: mem0-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mem0-config
  namespace: sophia-memory
data:
  mem0.yaml: |
    version: "0.1"

    llm:
      provider: "openai"
      config:
        model: "gpt-4"
        temperature: 0.1
        top_p: 1
        max_tokens: 2000

    embedder:
      provider: "openai"
      config:
        model: "text-embedding-3-large"

    vector_store:
      provider: "pinecone"
      config:
        metric: "cosine"
        dimension: 3072
        index_name: "sophia-mem0"

    history_db:
      provider: "postgresql"
      config:
        url: "${POSTGRES_URL}"

    cache:
      provider: "redis"
      config:
        url: "${REDIS_URL}"
        ttl: 3600

    version: "0.1.0"
