name: API Coverage Check

on:
  pull_request:
    paths:
      - 'config/mcp/**_coverage.yml'
      - 'scripts/validate_api_coverage.py'
      - '.github/workflows/api-coverage-check.yml'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Validate Source-Coverage Registry
        run: |
          python scripts/validate_api_coverage.py