name: Hygiene Scan
on:
  schedule:
    - cron: "0 3 * * 1"
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hygiene inventory
        run: bash scripts/generate_hygiene_inventory.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hygiene-inventory
          path: reports/hygiene_inventory_*.csv
