name: Unified Sophia AI Deployment

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options: ['staging', 'production']

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env-detect.outputs.environment }}
      is_production: ${{ steps.env-detect.outputs.is_production }}
    steps:
      - name: Detect Environment
        id: env-detect
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ENVIRONMENT="${{ github.event.inputs.environment }}"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENVIRONMENT="production"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            ENVIRONMENT="staging"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ENVIRONMENT="preview"
          fi
          
          IS_PRODUCTION="false"
          if [[ "$ENVIRONMENT" == "production" ]]; then
            IS_PRODUCTION="true"
          fi
          
          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT
          echo "is_production=${IS_PRODUCTION}" >> $GITHUB_OUTPUT
          echo "🎯 Environment: ${ENVIRONMENT}"

  deploy-platform:
    uses: ./.github/workflows/reusable-deploy-platform.yml
    needs: determine-environment
    with:
      environment: ${{ needs.determine-environment.outputs.environment }}
      is_production: ${{ needs.determine-environment.outputs.is_production }}
    secrets: inherit

  deploy-mcp-servers:
    uses: ./.github/workflows/reusable-deploy-mcp.yml
    needs: determine-environment
    with:
      environment: ${{ needs.determine-environment.outputs.environment }}
    secrets: inherit 