name: One-Time Artefact Audit
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run inventory script
        run: |
          pip install ripgrep csvkit
          python scripts/generate_one_time_inventory.py
      - name: Post inventory summary
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_INFRA_WEBHOOK }}
        run: |
          head -n 20 one_time_inventory.csv
          # curl -X POST --data-urlencode @one_time_inventory.csv $SLACK_WEBHOOK
