name: Quality Gates
on: [pull_request]

jobs:
  duplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: uv pip install pylint jscpd
      - run: python scripts/duplication_scan.py
