name: Reusable Platform Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      is_production:
        required: true
        type: boolean
    secrets:
      VERCEL_ACCESS_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID_PROD:
        required: true
      VERCEL_PROJECT_ID_STAGING:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true

env:
  PULUMI_ORG: scoobyjava-org
  DOCKER_REGISTRY: registry.digitalocean.com/sophia-ai

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install and Build
        working-directory: ./frontend
        run: |
          npm ci:
          npm run build:
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ inputs.is_production && secrets.VERCEL_PROJECT_ID_PROD || secrets.VERCEL_PROJECT_ID_STAGING }}
          working-directory: ./frontend
          production: ${{ inputs.is_production }}

  deploy-backend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: uv sync
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/sophia-backend:${{ github.sha }}
      - name: Deploy with Pulumi
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: ${{ env.PULUMI_ORG }}/sophia-ai-platform/${{ inputs.environment }}
          work-dir: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }} 