name: Reusable MCP Server Deployment

on
  workflow_call
    inputs
      environment
        required: true
        type: string

jobs
  determine-mcp-servers
    runs-on: ubuntu-latest
    outputs
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          SERVERS=$(ls -d mcp-servers/*/ | xargs -n 1 basename)
          echo "matrix={\"server\":[$(echo $SERVERS | sed 's/ /","/g' | sed 's/^/"/' | sed 's/$/"/')]}}" >> $GITHUB_OUTPUT

  deploy
    needs: determine-mcp-servers
    runs-on: ubuntu-latest
    strategy
      matrix: ${{ fromJson(needs.determine-mcp-servers.outputs.matrix) }}
    environment: ${{ inputs.environment }}
    steps
      - uses: actions/checkout@v4
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Build and Deploy ${{ matrix.server }}
        working-directory: ./mcp-servers/${{ matrix.server }}
        env
          COMMIT_SHA: ${{ github.sha }}
        run: |
          # Build Docker image
          docker build -t mcp-${{ matrix.server }}:${COMMIT_SHA} .
          # Push to registry would go here
          # Use Kustomize to apply environment-specific overlay
          kustomize build overlays/${{ inputs.environment }} | kubectl apply -f - 