name: Sync Secrets to Pulumi ESC

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: true
        default: 'Manual sync of organization secrets to Pulumi ESC'
  push:
    branches: [main]
    paths:
      - 'scripts/ci/sync_from_gh_to_pulumi.py'
      - '.github/workflows/sync_secrets.yml'

jobs:
  sync-secrets-to-pulumi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          # Install basic dependencies needed for the sync script
          uv add requests

      - name: Setup Pulumi CLI
        uses: pulumi/actions@v5

      - name: Validate Pulumi Access
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi login
          pulumi whoami
          echo "✅ Pulumi authentication successful"

      - name: Sync Secrets to Pulumi ESC
        run: python scripts/ci/sync_from_gh_to_pulumi.py
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

          # Core AI Services (Priority 1)
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GONG_ACCESS_KEY: ${{ secrets.GONG_ACCESS_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}

          # Gateway Services (Priority 1)
          PORTKEY_API_KEY: ${{ secrets.PORTKEY_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

          # Business Intelligence (Priority 1)
          HUBSPOT_ACCESS_TOKEN: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          ASANA_API_TOKEN: ${{ secrets.ASANA_API_TOKEN }}

          # Communication (Priority 1)
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
          SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}

          # Development Tools (Priority 1)
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          FIGMA_PAT: ${{ secrets.FIGMA_PAT }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}

          # Infrastructure (Priority 1)
          LAMBDA_API_KEY: ${{ secrets.LAMBDA_API_KEY }}
          LAMBDA_IP_ADDRESS: ${{ secrets.LAMBDA_IP_ADDRESS }}
          LAMBDA_SSH_PRIVATE_KEY: ${{ secrets.LAMBDA_SSH_PRIVATE_KEY }}

          # Snowflake Infrastructure (Complete)
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_DATABASE_PROD: ${{ secrets.SNOWFLAKE_DATABASE_PROD }}
          SNOWFLAKE_WAREHOUSE_ANALYTICS: ${{ secrets.SNOWFLAKE_WAREHOUSE_ANALYTICS }}
          SNOWFLAKE_ROLE_PROD: ${{ secrets.SNOWFLAKE_ROLE_PROD }}

          # Extended AI Services
          CODESTRAL_API_KEY: ${{ secrets.CODESTRAL_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          LLAMA_API_KEY: ${{ secrets.LLAMA_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          TOGETHER_AI_API_KEY: ${{ secrets.TOGETHER_AI_API_KEY }}
          VENICE_AI_API_KEY: ${{ secrets.VENICE_AI_API_KEY }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}

          # Vector Databases
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
          WEAVIATE_API_KEY: ${{ secrets.WEAVIATE_API_KEY }}
          WEAVIATE_GRPC_ENDPOINT: ${{ secrets.WEAVIATE_GRPC_ENDPOINT }}
          WEAVIATE_REST_ENDPOINT: ${{ secrets.WEAVIATE_REST_ENDPOINT }}
          WEAVIATE_URL: ${{ secrets.WEAVIATE_URL }}

          # Data Infrastructure
          REDIS_URL: ${{ secrets.REDIS_URL }}
          ESTUARY_ACCESS_TOKEN: ${{ secrets.ESTUARY_ACCESS_TOKEN }}
          AIRBYTE_ACCESS_TOKEN: ${{ secrets.AIRBYTE_ACCESS_TOKEN }}

          # Cloud Infrastructure
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}

          # Observability & Monitoring
          ARIZE_API_KEY: ${{ secrets.ARIZE_API_KEY }}
          ARIZE_SPACE_ID: ${{ secrets.ARIZE_SPACE_ID }}
          GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          GRAFANA_USERNAME: ${{ secrets.GRAFANA_USERNAME }}
          PROMETHEUS_URL: ${{ secrets.PROMETHEUS_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

          # Research & Data Collection
          APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
          BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
          EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          ZENROWS_API_KEY: ${{ secrets.ZENROWS_API_KEY }}
          TWINGLY_API_KEY: ${{ secrets.TWINGLY_API_KEY }}

          # Development & CI/CD
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_PERSONAL_ACCESS_TOKEN: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}
          NPM_API_TOKEN: ${{ secrets.NPM_API_TOKEN }}
          RETOOL_API_TOKEN: ${{ secrets.RETOOL_API_TOKEN }}

          # Integration Platforms
          PIPEDREAM_API_KEY: ${{ secrets.PIPEDREAM_API_KEY }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
          KONG_ACCESS_TOKEN: ${{ secrets.KONG_ACCESS_TOKEN }}

          # Business Tools
          SALESFORCE_ACCESS_TOKEN: ${{ secrets.SALESFORCE_ACCESS_TOKEN }}
          APOLLO_API_KEY: ${{ secrets.APOLLO_API_KEY }}
          PHANTOMBUSTER_API_KEY: ${{ secrets.PHANTOMBUSTER_API_KEY }}

          # Security & Encryption
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          BACKUP_ENCRYPTION_KEY: ${{ secrets.BACKUP_ENCRYPTION_KEY }}

          # Content & Media
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
          RECRAFT_API_KEY: ${{ secrets.RECRAFT_API_KEY }}

      - name: Upload Sync Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sync-report
          path: sync_report.json
          retention-days: 30

      - name: Display Sync Summary
        if: always()
        run: |
          if [ -f sync_report.json ]; then
            echo "📋 Sync Report Summary:"
            echo "======================="
            cat sync_report.json | python -m json.tool
          else
            echo "❌ Sync report not found"
          fi

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Secret sync failed!"
          echo "Check the workflow logs and sync report for details."
          echo "Some secrets may not be available in the organization secrets."
