name: Sync Secrets to Pulumi ESC

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: true
        default: 'Manual sync of organization secrets to Pulumi ESC'
  push:
    branches: [main]
    paths:
      - 'scripts/ci/sync_from_gh_to_pulumi.py'
      - '.github/workflows/sync_secrets.yml'

jobs:
  sync-secrets-to-pulumi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          # Install dependencies needed for the sync script
          pip install requests pulumi

      - name: Setup Pulumi CLI
        uses: pulumi/actions@v5

      - name: Validate Pulumi Access
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi login
          pulumi whoami
          echo "✅ Pulumi authentication successful"

      - name: Sync Secrets to Pulumi ESC
        run: python scripts/ci/sync_from_gh_to_pulumi.py
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

          # Core AI Services
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GONG_ACCESS_KEY: ${{ secrets.GONG_ACCESS_KEY }}
          GONG_ACCESS_KEY_SECRET: ${{ secrets.GONG_ACCESS_KEY_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          MEM0_API_KEY: ${{ secrets.MEM0_API_KEY }}

          # Gateway Services
          PORTKEY_API_KEY: ${{ secrets.PORTKEY_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

          # Business Intelligence
          HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}

          # Communication
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

          # Development Tools
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_APP_ID: ${{ secrets.GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
          FIGMA_PAT: ${{ secrets.FIGMA_PAT }}
          FIGMA_PROJECT_ID: ${{ secrets.FIGMA_PROJECT_ID }}
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}

          # Infrastructure
          LAMBDA_API_KEY: ${{ secrets.LAMBDA_API_KEY }}
          LAMBDA_LABS_API_KEY: ${{ secrets.LAMBDA_LABS_API_KEY }}
          LAMBDA_LABS_SSH_PRIVATE_KEY: ${{ secrets.LAMBDA_LABS_SSH_PRIVATE_KEY }}
          LAMBDA_LABS_SSH_KEY_NAME: ${{ secrets.LAMBDA_LABS_SSH_KEY_NAME }}
          LAMBDA_LABS_REGION: ${{ secrets.LAMBDA_LABS_REGION }}
          LAMBDA_LABS_INSTANCE_TYPE: ${{ secrets.LAMBDA_LABS_INSTANCE_TYPE }}
          LAMBDA_LABS_CLUSTER_SIZE: ${{ secrets.LAMBDA_LABS_CLUSTER_SIZE }}
          LAMBDA_LABS_MAX_CLUSTER_SIZE: ${{ secrets.LAMBDA_LABS_MAX_CLUSTER_SIZE }}
          LAMBDA_LABS_SHARED_FS_ID: ${{ secrets.LAMBDA_LABS_SHARED_FS_ID }}
          LAMBDA_LABS_SHARED_FS_MOUNT: ${{ secrets.LAMBDA_LABS_SHARED_FS_MOUNT }}
          LAMBDA_LABS_ASG_NAME: ${{ secrets.LAMBDA_LABS_ASG_NAME }}

          # Snowflake
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

          # Data Infrastructure
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          ESTUARY_API_TOKEN: ${{ secrets.ESTUARY_API_TOKEN }}

          # Cloud Infrastructure
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}

          # Development & CI/CD
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

          # Monitoring
          GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}

          # Vector Databases
          WEAVIATE_API_KEY: ${{ secrets.WEAVIATE_API_KEY }}
          WEAVIATE_URL: ${{ secrets.WEAVIATE_URL }}

      - name: Upload Sync Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sync-report
          path: sync_report.json
          retention-days: 30

      - name: Display Sync Summary
        if: always()
        run: |
          if [ -f sync_report.json ]; then
            echo "📋 Sync Report Summary:"
            echo "======================="
            cat sync_report.json | python -m json.tool
          else
            echo "❌ Sync report not found"
          fi

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Secret sync failed!"
          echo "Check the workflow logs and sync report for details."
          echo "Some secrets may not be available in the organization secrets."
