name: 🔐 Sync Secrets to Pulumi ESC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM UTC
  push:
    paths:
      - 'config/pulumi/secret_map.yaml'
      - '.github/workflows/sync_secrets.yml'

jobs:
  sync:
    name: Sync Organization Secrets
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyyaml pulumi httpx structlog

      - name: Sync secrets to Pulumi ESC
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          # Map all GitHub secrets to environment variables
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GONG_ACCESS_KEY: ${{ secrets.GONG_ACCESS_KEY }}
          GONG_ACCESS_KEY_SECRET: ${{ secrets.GONG_ACCESS_KEY_SECRET }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          LAMBDA_API_KEY: ${{ secrets.LAMBDA_LABS_API_KEY }}
          LAMBDA_SSH_KEY: ${{ secrets.LAMBDA_SSH_KEY }}
          LAMBDA_SSH_PRIVATE_KEY: ${{ secrets.LAMBDA_SSH_PRIVATE_KEY }}
          LAMBDA_API_ENDPOINT: ${{ secrets.LAMBDA_API_ENDPOINT }}
          # DOCKER HUB - FIXED NAMES
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # Changed from DOCKER_HUB_USERNAME
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}        # Changed from DOCKER_HUB_ACCESS_TOKEN
          # Other secrets
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          ASANA_API_TOKEN: ${{ secrets.ASANA_API_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          AWS_DEPLOY_ROLE_ARN: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          FIGMA_PAT: ${{ secrets.FIGMA_PAT }}
          FIGMA_PROJECT_ID: ${{ secrets.FIGMA_PROJECT_ID }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PORTKEY_API_KEY: ${{ secrets.PORTKEY_API_KEY }}
          WEAVIATE_API_KEY: ${{ secrets.WEAVIATE_API_KEY }}
          WEAVIATE_URL: ${{ secrets.WEAVIATE_URL }}
        run: |
          # Export all secrets as SECRET_* environment variables
          export SECRET_OPENAI_API_KEY="${OPENAI_API_KEY}"
          export SECRET_ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}"
          export SECRET_GONG_ACCESS_KEY="${GONG_ACCESS_KEY}"
          export SECRET_GONG_ACCESS_KEY_SECRET="${GONG_ACCESS_KEY_SECRET}"
          export SECRET_PINECONE_API_KEY="${PINECONE_API_KEY}"
          export SECRET_SNOWFLAKE_ACCOUNT="${SNOWFLAKE_ACCOUNT}"
          export SECRET_SNOWFLAKE_USER="${SNOWFLAKE_USER}"
          export SECRET_SNOWFLAKE_PASSWORD="${SNOWFLAKE_PASSWORD}"
          export SECRET_SNOWFLAKE_WAREHOUSE="${SNOWFLAKE_WAREHOUSE}"
          export SECRET_SNOWFLAKE_DATABASE="${SNOWFLAKE_DATABASE}"
          export SECRET_SNOWFLAKE_SCHEMA="${SNOWFLAKE_SCHEMA}"
          export SECRET_SNOWFLAKE_ROLE="${SNOWFLAKE_ROLE}"
          export SECRET_LAMBDA_API_KEY="${LAMBDA_API_KEY}"
          export SECRET_LAMBDA_SSH_KEY="${LAMBDA_SSH_KEY}"
          export SECRET_LAMBDA_SSH_PRIVATE_KEY="${LAMBDA_SSH_PRIVATE_KEY}"
          export SECRET_LAMBDA_API_ENDPOINT="${LAMBDA_API_ENDPOINT}"
          export SECRET_DOCKER_USERNAME="${DOCKER_USERNAME}"
          export SECRET_DOCKER_TOKEN="${DOCKER_TOKEN}"
          export SECRET_GITHUB_TOKEN="${GITHUB_TOKEN}"
          export SECRET_SLACK_WEBHOOK="${SLACK_WEBHOOK}"
          export SECRET_SLACK_BOT_TOKEN="${SLACK_BOT_TOKEN}"
          export SECRET_HUBSPOT_API_KEY="${HUBSPOT_API_KEY}"
          export SECRET_LINEAR_API_KEY="${LINEAR_API_KEY}"
          export SECRET_ASANA_API_TOKEN="${ASANA_API_TOKEN}"
          export SECRET_NOTION_API_KEY="${NOTION_API_KEY}"
          export SECRET_VERCEL_TOKEN="${VERCEL_TOKEN}"
          export SECRET_VERCEL_ORG_ID="${VERCEL_ORG_ID}"
          export SECRET_VERCEL_PROJECT_ID="${VERCEL_PROJECT_ID}"
          export SECRET_GRAFANA_API_KEY="${GRAFANA_API_KEY}"
          export SECRET_GRAFANA_URL="${GRAFANA_URL}"
          export SECRET_POSTGRES_USER="${POSTGRES_USER}"
          export SECRET_POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
          export SECRET_POSTGRES_DB="${POSTGRES_DB}"
          export SECRET_REDIS_PASSWORD="${REDIS_PASSWORD}"
          export SECRET_AWS_DEPLOY_ROLE_ARN="${AWS_DEPLOY_ROLE_ARN}"
          export SECRET_FIGMA_PAT="${FIGMA_PAT}"
          export SECRET_FIGMA_PROJECT_ID="${FIGMA_PROJECT_ID}"
          export SECRET_OPENROUTER_API_KEY="${OPENROUTER_API_KEY}"
          export SECRET_PORTKEY_API_KEY="${PORTKEY_API_KEY}"
          export SECRET_WEAVIATE_API_KEY="${WEAVIATE_API_KEY}"
          export SECRET_WEAVIATE_URL="${WEAVIATE_URL}"
          
          # Use the correct sync script
          python scripts/ci/sync_secrets_to_esc.py

      - name: Validate sync
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          python scripts/ci_cd_rehab/validate_secrets.py \
            --environment production \
            --required-secrets config/pulumi/required_secrets.yaml

      - name: Generate sync report
        if: always()
        run: |
          mkdir -p reports
          python scripts/ci_cd_rehab/generate_sync_report.py > reports/sync_report.json

      - name: Upload sync report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sync-report-${{ github.run_id }}
          path: reports/sync_report.json
          retention-days: 30

      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: failure
          text: |
            ⚠️ Secret sync to Pulumi ESC failed!
            Workflow: ${{ github.workflow }}
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
